In [1]:
# !pip install cities_coordinates

In [2]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler

#https://github.com/sofzer/cities_coordinates
from cities_coordinates import CityCoordinator
c = CityCoordinator()

<div class="alert alert-block alert-info">

# Data Visualization - ATP Stats
    
</div>

- Ana Sofia Mendonça, number: 20220678
- Beatriz Sousa, number: 20220674
- Cláudia Rocha, number: r20191249
- Susana Dias, number: 20220198

<a id = "toc"></a>

1. [Import the datasets](#import-datasets)
2. [Data understanding and preparation - Tournaments dataset](#understanding-preparation-tournaments)
3. [Data understanding and preparation - Match Scores dataset](#understanding-preparation-match-scores)
4. [Data understanding and preparation - Match Stats dataset](#understanding-preparation-match-stats)
5. [Merging the stats dataset with the score dataset](#merging-match-scores-stats)

<a id = "import-datasets"></a>

## 1. Import the datasets

[Back to TOC](#toc)

In [3]:
# defining the path to get the datasets from github

path_datasets = 'https://raw.githubusercontent.com/serve-and-volley/atp-world-tour-tennis-data/master/csv/'
path_tournaments = '1_tournaments/'
path_match_scores = '2_match_scores/'
path_match_stats = '3_match_stats/'

In [4]:
# defining the name of the variables in the tournaments datasets, in order to define the header
tournaments_header = ['tourney_year_id', 'tourney_order', 'tourney_type', 'tourney_name', 'tourney_id', 'tourney_slug', 'tourney_location', 'tourney_date', 'year', 'tourney_month', 'tourney_day', 'tourney_singles_draw', 'tourney_doubles_draw', 'tourney_conditions', 'tourney_surface', 'tourney_fin_commit_raw', 'currency', 'tourney_fin_commit', 'tourney_url_suffix', 'singles_winner_name', 'singles_winner_url', 'singles_winner_player_slug', 'singles_winner_player_id', 'doubles_winner_1_name', 'doubles_winner_1_url', 'doubles_winner_1_player_slug', 'doubles_winner_1_player_id', 'doubles_winner_2_name', 'doubles_winner_2_url', 'doubles_winner_2_player_slug', 'doubles_winner_2_player_id']

# importing the datasets
tournaments = pd.read_csv(path_datasets + path_tournaments + 'tournaments_2010-2019.csv', names = tournaments_header)

In [5]:
# defining the name of the variables in the match scores datasets, in order to define the header
match_scores_header = ['tourney_year_id', 'tourney_order', 'tourney_name', 'tourney_slug', 'tourney_url_suffix', 'start_date', 'start_year', 'start_month', 'start_day', 'end_date', 'end_year', 'end_month', 'end_day', 'currency', 'prize_money', 'match_index', 'tourney_round_name', 'round_order', 'match_order', 'winner_name', 'winner_player_id', 'winner_slug', 'loser_name', 'loser_player_id', 'loser_slug', 'winner_seed', 'loser_seed', 'match_score_tiebreaks', 'winner_sets_won', 'loser_sets_won', 'winner_games_won', 'loser_games_won', 'winner_tiebreaks_won', 'loser_tiebreaks_won', 'match_id', 'match_stats_url_suffix']

# importing the datasets 
match_scores = pd.read_csv(path_datasets + path_match_scores + 'match_scores_2010-2019.csv', names = match_scores_header)

In [6]:
# defining the name of the variables in the match stats datasets, in order to define the header
match_stats_header = ['match_id', 'tourney_slug', 'match_stats_url_suffix', 'match_time', 'match_duration', 'winner_slug', 'winner_serve_rating', 'winner_aces', 'winner_double_faults', 'winner_first_serves_in', 'winner_first_serves_total', 'winner_first_serve_points_won', 'winner_first_serve_points_total', 'winner_second_serve_points_won', 'winner_second_serve_points_total', 'winner_break_points_saved', 'winner_break_points_serve_total', 'winner_service_games_played', 'winner_return_rating', 'winner_first_serve_return_won', 'winner_first_serve_return_total', 'winner_second_serve_return_won', 'winner_second_serve_return_total', 'winner_break_points_converted', 'winner_break_points_return_total', 'winner_return_games_played', 'winner_service_points_won', 'winner_service_points_total', 'winner_return_points_won', 'winner_return_points_total', 'winner_total_points_won', 'winner_total_points_total', 'loser_slug', 'loser_serve_rating', 'loser_aces', 'loser_double_faults', 'loser_first_serves_in', 'loser_first_serves_total', 'loser_first_serve_points_won', 'loser_first_serve_points_total', 'loser_second_serve_points_won', 'loser_second_serve_points_total', 'loser_break_points_saved', 'loser_break_points_serve_total', 'loser_service_games_played', 'loser_return_rating', 'loser_first_serve_return_won', 'loser_first_serve_return_total', 'loser_second_serve_return_won', 'loser_second_serve_return_total', 'loser_break_points_converted', 'loser_break_points_return_total', 'loser_return_games_played', 'loser_service_points_won', 'loser_service_points_total', 'loser_return_points_won', 'loser_return_points_total', 'loser_total_points_won', 'loser_total_points_total']

# importing the datasets 
match_stats_2010 = pd.read_csv(path_datasets + path_match_stats + 'match_stats_2010.csv', names = match_stats_header)
match_stats_2011 = pd.read_csv(path_datasets + path_match_stats + 'match_stats_2011.csv', names = match_stats_header)
match_stats_2012 = pd.read_csv(path_datasets + path_match_stats + 'match_stats_2012.csv', names = match_stats_header)
match_stats_2013 = pd.read_csv(path_datasets + path_match_stats + 'match_stats_2013.csv', names = match_stats_header)
match_stats_2014 = pd.read_csv(path_datasets + path_match_stats + 'match_stats_2014.csv', names = match_stats_header)
match_stats_2015 = pd.read_csv(path_datasets + path_match_stats + 'match_stats_2015.csv', names = match_stats_header)
match_stats_2016 = pd.read_csv(path_datasets + path_match_stats + 'match_stats_2016.csv', names = match_stats_header)
match_stats_2017 = pd.read_csv(path_datasets + path_match_stats + 'match_stats_2017.csv', names = match_stats_header)
match_stats_2018 = pd.read_csv(path_datasets + path_match_stats + 'match_stats_2018.csv', names = match_stats_header)
match_stats_2019 = pd.read_csv(path_datasets + path_match_stats + 'match_stats_2019.csv', names = match_stats_header)

# stack them into one dataset
match_stats = pd.concat([match_stats_2010, match_stats_2011, match_stats_2012, match_stats_2013, match_stats_2014, match_stats_2015, match_stats_2016, match_stats_2017, match_stats_2018, match_stats_2019], ignore_index = True)

<a id = "understanding-preparation-tournaments"></a>

## 2. Data understanding and preparation - Tournaments datasets

[Back to TOC](#toc)

In [7]:
tournaments.T

0    \
tourney_year_id                                                   2010-339   
tourney_order                                                            1   
tourney_type                                                       ATP 250   
tourney_name                                                      Brisbane   
tourney_id                                                             339   
tourney_slug                                                      brisbane   
tourney_location                                                  Brisbane   
tourney_date                                                    2010.01.03   
year                                                                  2010   
tourney_month                                                            1   
tourney_day                                                              3   
tourney_singles_draw                                                    32   
tourney_doubles_draw                                                    16   
tourney_conditions                                                 Outdoor   
tourney_surface                                                       Hard   
tourney_fin_commit_raw                                            $424,250   
currency                                                               USD   
tourney_fin_commit                                                424250.0   
tourney_url_suffix            /en/scores/archive/brisbane/339/2010/results   
singles_winner_name                                           Andy Roddick   
singles_winner_url                  /en/players/andy-roddick/r485/overview   
singles_winner_player_slug                                    andy-roddick   
singles_winner_player_id                                              r485   
doubles_winner_1_name                                        Jeremy Chardy   
doubles_winner_1_url               /en/players/jeremy-chardy/ca12/overview   
doubles_winner_1_player_slug                                 jeremy-chardy   
doubles_winner_1_player_id                                            ca12   
doubles_winner_2_name                                         Marc Gicquel   
doubles_winner_2_url                /en/players/marc-gicquel/g436/overview   
doubles_winner_2_player_slug                                  marc-gicquel   
doubles_winner_2_player_id                                            g436   

                                                                           1    \
tourney_year_id                                                       2010-451   
tourney_order                                                                2   
tourney_type                                                           ATP 250   
tourney_name                                                              Doha   
tourney_id                                                                 451   
tourney_slug                                                              doha   
tourney_location                                                          Doha   
tourney_date                                                        2010.01.04   
year                                                                      2010   
tourney_month                                                                1   
tourney_day                                                                  4   
tourney_singles_draw                                                        32   
tourney_doubles_draw                                                        16   
tourney_conditions                                                     Outdoor   
tourney_surface                                                           Hard   
tourney_fin_commit_raw                                              $1,110,250   
currency                                                                   USD   
tourney_fin_commit                                                   1110250.0   
tourney_url_suff

#### Variables:

- `tourney_year_id` 
- `tourney_order`: in terms of the calendar.
- `tourney_type`: *Grand Slam Tournaments* (the matches are played as best-of-five sets and offer 2000 points), *ATP Finals* (the matches are played as best-of-three sets and offer 1500 points), *ATP Masters 1000* (the matches are played as best-of-three sets and offer 1000 points), *ATP 500 Tournaments* (the matches are played as best-of-three sets and offer 500 points), or *ATP 250 Tournaments* (the matches are played as best-of-three sets and offer 250 points).
- `tourney_name`
- `tourney_id`
- `tourney_slug`
- `tourney_location`
- `tourney_date`
- `year`
- `tourney_month`
- `tourney_day`
- `tourney_singles_draw`: number of players who will compete in the tournament's main singles draw.
- `tourney_doubles_draw`: number of teams who will compete in the tournament's main doubles draw.
- `tourney_conditions`: whether it is an indoor tournament or outdoor tournament.
- `tourney_surface`: refers to the type of playing surface that the tournament is played on. There are 4 main types of surfaces: *hard courts* (made of asphalt or concrete and coated with acrylic material, and provide a relatively fast and predictable bounce), *clay courts* (made of crushed brick, shale, or stone, and provide a slower and higher bounce than hard courts; players must slide into their shots on clay courts, and the surface is known for producing long and physically demanding matches), *grass courts* (are the fastest surface and provide a low and skidding bounce; they require players to have good footwork and quick reflexes, as the ball tends to stay low, making it difficult for players to hit powerful shots), and *carpet courts* (are an indoor surface, and provide a relatively fast and low bounce; not very used).
- `tourney_fin_commit_raw`: total amount of prize money that the tournament organizers commit to paying out to the players, including the prize money for both the singles and doubles events, as well as any fees or bonuses that the players may receive for participating in the tournament.
- `currency`
- `tourney_fin_commit`: the same as `tourney_fin_commit_raw`, but stored as a number in the dataset.
- `tourney_url_suffix`
- `singles_winner_name`
- `singles_winner_url`
- `singles_winner_player_slug`
- `singles_winner_player_id`
- `doubles_winner_1_name`
- `doubles_winner_1_url`
- `doubles_winner_1_player_slug`
- `doubles_winner_1_player_id`
- `doubles_winner_2_name`
- `doubles_winner_2_url`
- `doubles_winner_2_player_slug`
- `doubles_winner_2_player_id`

In [8]:
# checking the shape of the dataset

tournaments.shape

(668, 31)

#### Data types:

In [9]:
# checking the types of the variables, as well as the number of non-null observations in each variable

tournaments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 668 entries, 0 to 667
Data columns (total 31 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   tourney_year_id               668 non-null    object 
 1   tourney_order                 668 non-null    int64  
 2   tourney_type                  663 non-null    object 
 3   tourney_name                  668 non-null    object 
 4   tourney_id                    668 non-null    int64  
 5   tourney_slug                  668 non-null    object 
 6   tourney_location              667 non-null    object 
 7   tourney_date                  668 non-null    object 
 8   year                          668 non-null    int64  
 9   tourney_month                 668 non-null    int64  
 10  tourney_day                   668 non-null    int64  
 11  tourney_singles_draw          668 non-null    int64  
 12  tourney_doubles_draw          668 non-null    int64  
 13  tourn

Some tournaments have the `tourney_location` and `tourney_type` missing, and some have the data regarding the Total Financial Commitment missing. The winners are also missing for some tournaments, maybe because the time range of this dataset includes the tournaments that were not played due to the Covid-19 pandemic.

Regarding `tourney_date`, it is stored as a string, and should be store as a date.

In [10]:
# storing correctly the variable regarding dates

tournaments['tourney_date'] = pd.to_datetime(tournaments['tourney_date'], format = '%Y.%m.%d')

#### Descriptive statistics:

In [11]:
tournaments.describe().T

count          mean           std       min       25%  \
tourney_order         668.0  3.391467e+01  1.932132e+01       1.0      17.0   
tourney_id            668.0  1.524737e+03  2.351811e+03      96.0     375.0   
year                  668.0  2.014542e+03  2.883502e+00    2010.0    2012.0   
tourney_month         668.0  5.715569e+00  3.126508e+00       1.0       2.0   
tourney_day           668.0  1.606287e+01  8.515033e+00       1.0       9.0   
tourney_singles_draw  668.0  4.075449e+01  2.638805e+01       8.0      28.0   
tourney_doubles_draw  668.0  2.020958e+01  1.185537e+01       0.0      16.0   
tourney_fin_commit    663.0  2.458502e+06  4.001018e+06  407250.0  520177.5   

                           50%        75%         max  
tourney_order             34.0       51.0        69.0  
tourney_id               451.0      742.5      9210.0  
year                    2015.0     2017.0      2019.0  
tourney_month              6.0        8.0        12.0  
tourney_day               16.0       23.0        31.0  
tourney_singles_draw      32.0       48.0       128.0  
tourney_doubles_draw      16.0       16.0        64.0  
tourney_fin_commit    727685.0  2341990.0  29687000.0

In [12]:
tournaments.describe(include = ['O']).T

count unique  \
tourney_year_id                668    668   
tourney_type                   663      7   
tourney_name                   668     96   
tourney_slug                   668     96   
tourney_location               667    126   
tourney_conditions             668      2   
tourney_surface                668      3   
tourney_fin_commit_raw         663    413   
currency                       663      4   
tourney_url_suffix             668    668   
singles_winner_name            664    126   
singles_winner_url             664    126   
singles_winner_player_slug     664    126   
singles_winner_player_id       664    126   
doubles_winner_1_name          661    153   
doubles_winner_1_url           661    153   
doubles_winner_1_player_slug   661    153   
doubles_winner_1_player_id     661    153   
doubles_winner_2_name          661    144   
doubles_winner_2_url           661    144   
doubles_winner_2_player_slug   661    144   
doubles_winner_2_player_id     661    144   

                                                                       top  \
tourney_year_id                                                   2010-339   
tourney_type                                                       ATP 250   
tourney_name                                                      Brisbane   
tourney_slug                                                        london   
tourney_location                                     London, Great Britain   
tourney_conditions                                                 Outdoor   
tourney_surface                                                       Hard   
tourney_fin_commit_raw                                            €450,000   
currency                                                               USD   
tourney_url_suffix            /en/scores/archive/brisbane/339/2010/results   
singles_winner_name                                         Novak Djokovic   
singles_winner_url                /en/players/novak-djokovic/d643/overview   
singles_winner_player_slug                                  novak-djokovic   
singles_winner_player_id                                              d643   
doubles_winner_1_name                                            Bob Bryan   
doubles_winner_1_url                   /en/players/bob-bryan/b588/overview   
doubles_winner_1_player_slug                                     bob-bryan   
doubles_winner_1_player_id                                            b588   
doubles_winner_2_name                                           Mike Bryan   
doubles_winner_2_url                  /en/players/mike-bryan/b589/overview   
doubles_winner_2_player_slug                                    mike-bryan   
doubles_winner_2_player_id                                            b589   

                             freq  
tourney_year_id                 1  
tourney_type                  397  
tourney_name                   10  
tourney_slug                   11  
tourney_location               30  
tourney_conditions            502  
tourney_surface               378  
tourney_fin_commit_raw         32  
currency                      325  
tourney_url_suffix              1  
singles_winner_name            61  
singles_winner_url             61  
singles_winner_player_slug     61  
singles_winner_player_id       61  
doubles_winner_1_name          63  
doubles_winner_1_url           63  
doubles_winner_1_player_slug   63  
doubles_winner_1_player_id     63  
doubles_winner_2_name          63  
doubles_winner_2_url           63  
doubles_winner_2_player_slug   63  
doubles_winner_2_player_id     63

From this descriptive statistics, it can be seen that the mean of players in the singles tournaments is 40 for and the mean of teams in the doubles tournaments is 20. As for the Total Financial Commitment, it is, on average, 2 milion, however this must be standardized, since the values are represented in different currencies. The majority of the tournaments are in outdoor conditions, and played in hard courts. The most successful singles player in the male Tennis circuit is Novak Djokovic during this period of time.

#### Do not make sense for our analysis:

In [13]:
tournaments['tourney_type'].value_counts()

ATP 250            397
ATP 500            120
Masters 1000        90
Grand Slam          40
ATP Finals          10
Laver Cup            3
Next Gen Finals      3
Name: tourney_type, dtype: int64

The Laver Cup is a competition that features a team format between Europe and the rest of the world. Since the Laver Cup is not a part of the ATP Tour, it does not award ranking points to players, therefore it will not be considered for this analysis.

Also, the ATP Cup is a men's professional tennis tournament that features national teams from different countries competing against each other. It is a team competition, with players representing their countries, and altough it awards ranking points, also it will not be considered since it is a teams competition.

In [14]:
# dropping the tournaments that fall into the category found before

tournaments = tournaments[tournaments['tourney_type'] != 'Laver Cup']
tournaments = tournaments[tournaments['tourney_type'] != 'ATP Cup']

Also, we have some other variables that do not make a lot of sense to mantain, for example `tourney_fin_commit_raw`, since this is a variable that do not add new information (as we have the same information but properly encoded in `tourney_fin_commit` and `currency`). As for the websites provided in the dataset (in variables `tourney_url_suffix`, `singles_winner_url`, `doubles_winner_1_url`, `doubles_winner_2_url`), they are irrelevant for our analysis, therefore will be deleted.

In [15]:
# droping the variables as explained above

tournaments.drop(columns = ['tourney_fin_commit_raw', 'tourney_url_suffix', 'singles_winner_url', 'doubles_winner_1_url', 'doubles_winner_2_url'], inplace = True)

As we already have the dates stored of the tournaments stored in a variable (properly encoded), it does not make sense to have two additional variables with month, and day. Therefore, these variables (`tourney_month`, `tourney_day`) should be deleted.

In [16]:
# droping the variables as explained above

tournaments.drop(columns = ['tourney_month', 'tourney_day'], inplace = True)

#### Missing values:

In [17]:
# creating a copy to solve the problems with missing values

tournaments_missing = tournaments.copy()

In [18]:
# replacing other types of missing values not recognized by pandas with NaN and checking again the number of missing values

missing_values = ['n/a', 'na', '--', '', 'unknown', 'Unknown']

tournaments_missing.replace(missing_values, np.nan, inplace = True)
tournaments_missing.isna().sum()

tourney_year_id                 0
tourney_order                   0
tourney_type                    5
tourney_name                    0
tourney_id                      0
tourney_slug                    0
tourney_location                1
tourney_date                    0
year                            0
tourney_singles_draw            0
tourney_doubles_draw            0
tourney_conditions              0
tourney_surface                 0
currency                        2
tourney_fin_commit              2
singles_winner_name             1
singles_winner_player_slug      1
singles_winner_player_id        1
doubles_winner_1_name           4
doubles_winner_1_player_slug    4
doubles_winner_1_player_id      4
doubles_winner_2_name           4
doubles_winner_2_player_slug    4
doubles_winner_2_player_id      4
dtype: int64

In [19]:
# seeing rows with NaNs

tournaments_nans_index = tournaments_missing.isna().any(axis = 1)
tournaments_missing[tournaments_nans_index].T

29                   65   \
tourney_year_id                              2010-615             2010-605   
tourney_order                                      30                   66   
tourney_type                                      NaN           ATP Finals   
tourney_name                  World Team Championship           ATP Finals   
tourney_id                                        615                  605   
tourney_slug                               dusseldorf           atp-finals   
tourney_location                           Dusseldorf                  NaN   
tourney_date                      2010-05-16 00:00:00  2010-11-21 00:00:00   
year                                             2010                 2010   
tourney_singles_draw                               32                    8   
tourney_doubles_draw                               16                    8   
tourney_conditions                            Outdoor               Indoor   
tourney_surface                                  Clay                 Hard   
currency                                          EUR                  USD   
tourney_fin_commit                          1350000.0            5070000.0   
singles_winner_name                       Juan Monaco        Roger Federer   
singles_winner_player_slug                juan-monaco        roger-federer   
singles_winner_player_id                         ma21                 f324   
doubles_winner_1_name                       Bob Bryan        Daniel Nestor   
doubles_winner_1_player_slug                bob-bryan        daniel-nestor   
doubles_winner_1_player_id                       b588                 n210   
doubles_winner_2_name                      Mike Bryan       Nenad Zimonjic   
doubles_winner_2_player_slug               mike-bryan       nenad-zimonjic   
doubles_winner_2_player_id                       b589                 z072   

                                                  95   \
tourney_year_id                              2011-615   
tourney_order                                      30   
tourney_type                                      NaN   
tourney_name                  World Team Championship   
tourney_id                                        615   
tourney_slug                               dusseldorf   
tourney_location                  Dusseldorf, Germany   
tourney_date                      2011-05-15 00:00:00   
year                                             2011   
tourney_singles_draw                               32   
tourney_doubles_draw                               16   
tourney_conditions                            Outdoor   
tourney_surface                                  Clay   
currency                                          EUR   
tourney_fin_commit                          1100000.0   
singles_winner_name                Juan Ignacio Chela   
singles_winner_player_slug         juan-ignacio-chela   
singles_winner_player_id                         c514   
doubles_winner_1_name           Philipp Kohlschreiber   
doubles_winner_1_player_slug    philipp-kohlschreiber   
doubles_winner_1_player_id                       k435   
doubles_winner_2_name              Philipp Petzschner   
doubles_winner_2_player_slug       philipp-petzschner   
doubles_winner_2_player_id                       p624   

                                                  162                    179  \
tourney_year_id                              2012-615                2012-96   
tourney_order                                      31                     48   
tourney_type                                      NaN                    NaN   
tourney_name                  World Team Championship        London Olympics   
tourney_id                                        615                     96   
tourney_slug                               dusseldorf                 london   
tourney_location                  Dusseldorf, Germany  London, Great Britain   
tourney_date                     

In [20]:
# seeing missing values in the type variable

tournaments_missing[tournaments_missing['tourney_type'].isna()]

tourney_year_id  tourney_order tourney_type                  tourney_name  \
29         2010-615             30          NaN       World Team Championship   
95         2011-615             30          NaN       World Team Championship   
162        2012-615             31          NaN       World Team Championship   
179         2012-96             48          NaN               London Olympics   
443         2016-96             49          NaN  Rio de Janeiro Olympic Games   

     tourney_id    tourney_slug        tourney_location tourney_date  year  \
29          615      dusseldorf              Dusseldorf   2010-05-16  2010   
95          615      dusseldorf     Dusseldorf, Germany   2011-05-15  2011   
162         615      dusseldorf     Dusseldorf, Germany   2012-05-20  2012   
179          96          london   London, Great Britain   2012-07-25  2012   
443          96  rio-de-janeiro  Rio de Janeiro, Brazil   2016-08-04  2016   

     tourney_singles_draw  ...  tourney_fin_commit singles_winner_name  \
29                     32  ...           1350000.0         Juan Monaco   
95                     32  ...           1100000.0  Juan Ignacio Chela   
162                    32  ...           1300000.0                 NaN   
179                    64  ...                 NaN         Andy Murray   
443                    64  ...                 NaN         Andy Murray   

    singles_winner_player_slug singles_winner_player_id  \
29                 juan-monaco                     ma21   
95          juan-ignacio-chela                     c514   
162                        NaN                      NaN   
179                andy-murray                     mc10   
443                andy-murray                     mc10   

     doubles_winner_1_name doubles_winner_1_player_slug  \
29               Bob Bryan                    bob-bryan   
95   Philipp Kohlschreiber        philipp-kohlschreiber   
162                    NaN                          NaN   
179              Bob Bryan                    bob-bryan   
443             Marc Lopez                   marc-lopez   

    doubles_winner_1_player_id doubles_winner_2_name  \
29                        b588            Mike Bryan   
95                        k435    Philipp Petzschner   
162                        NaN                   NaN   
179                       b588            Mike Bryan   
443                       l480          Rafael Nadal   

    doubles_winner_2_player_slug doubles_winner_2_player_id  
29                    mike-bryan                       b589  
95            philipp-petzschner                       p624  
162                          NaN                        NaN  
179                   mike-bryan                       b589  
443                 rafael-nadal                       n409  

[5 rows x 24 columns]

Since we are not considering for the analysis the competitions that do not award points or are teams competitions, we will delete the Olympics and the World Team Championship.

In [21]:
# deleting the observations as explained before

tournaments_missing.dropna(subset = ['tourney_type'], inplace = True)

In [22]:
# seeing missing values in the location variable

tournaments_missing[tournaments_missing['tourney_location'].isna()]

tourney_year_id  tourney_order tourney_type tourney_name  tourney_id  \
65        2010-605             66   ATP Finals   ATP Finals         605   

   tourney_slug tourney_location tourney_date  year  tourney_singles_draw  \
65   atp-finals              NaN   2010-11-21  2010                     8   

    ...  tourney_fin_commit singles_winner_name singles_winner_player_slug  \
65  ...           5070000.0       Roger Federer              roger-federer   

   singles_winner_player_id  doubles_winner_1_name  \
65                     f324          Daniel Nestor   

   doubles_winner_1_player_slug doubles_winner_1_player_id  \
65                daniel-nestor                       n210   

   doubles_winner_2_name doubles_winner_2_player_slug  \
65        Nenad Zimonjic               nenad-zimonjic   

   doubles_winner_2_player_id  
65                       z072  

[1 rows x 24 columns]

As it can be seen, the tournament that misses the location is "2010 ATP World Tour Finals". So, after a quick search (https://www.bbc.co.uk/programmes/b00wkcqm) we found that they were hosted in London, Great Britain.

In [23]:
# inputting the missing value

tournaments_missing.loc[65, 'tourney_location'] = 'London, Great Britain'

In [24]:
# seeing missing values in the doubles winner variable

tournaments_missing[tournaments_missing['doubles_winner_1_name'].isna()]

tourney_year_id  tourney_order     tourney_type         tourney_name  \
529       2017-7696             68  Next Gen Finals  Next Gen ATP Finals   
598       2018-7696             68  Next Gen Finals  Next Gen ATP Finals   
666       2019-7696             67  Next Gen Finals  Next Gen ATP Finals   

     tourney_id         tourney_slug tourney_location tourney_date  year  \
529        7696  next-gen-atp-finals     Milan, Italy   2017-11-07  2017   
598        7696  next-gen-atp-finals     Milan, Italy   2018-11-06  2018   
666        7696  next-gen-atp-finals     Milan, Italy   2019-11-05  2019   

     tourney_singles_draw  ...  tourney_fin_commit singles_winner_name  \
529                     8  ...           1275000.0         Hyeon Chung   
598                     8  ...           1335000.0  Stefanos Tsitsipas   
666                     8  ...           1400000.0       Jannik Sinner   

    singles_winner_player_slug singles_winner_player_id  \
529                hyeon-chung                     ch27   
598         stefanos-tsitsipas                     te51   
666              jannik-sinner                     s0ag   

     doubles_winner_1_name doubles_winner_1_player_slug  \
529                    NaN                          NaN   
598                    NaN                          NaN   
666                    NaN                          NaN   

    doubles_winner_1_player_id doubles_winner_2_name  \
529                        NaN                   NaN   
598                        NaN                   NaN   
666                        NaN                   NaN   

    doubles_winner_2_player_slug doubles_winner_2_player_id  
529                          NaN                        NaN  
598                          NaN                        NaN  
666                          NaN                        NaN  

[3 rows x 24 columns]

The Next Gen ATP Finals is a men's professional tennis tournament that features only a singles competition. The tournament is specifically designed to showcase the top young male players aged 21 and under, based on their ATP rankings. The format of the tournament is also unique, with shorter sets, no lets, no advantage scoring, and a shot clock to speed up the pace of play. So, these missing values are not an error, so, we can inpute them.

In [25]:
# inputting the missing values

tournaments_missing.loc[tournaments_missing['doubles_winner_1_name'].isna(), ['doubles_winner_1_name', 'doubles_winner_1_player_slug', 'doubles_winner_1_player_id', 'doubles_winner_2_name', 'doubles_winner_2_player_slug', 'doubles_winner_2_player_id']] = 'There is no doubles competition'

In [26]:
# checking that there are no more missing values

tournaments_missing.isna().sum()

tourney_year_id                 0
tourney_order                   0
tourney_type                    0
tourney_name                    0
tourney_id                      0
tourney_slug                    0
tourney_location                0
tourney_date                    0
year                            0
tourney_singles_draw            0
tourney_doubles_draw            0
tourney_conditions              0
tourney_surface                 0
currency                        0
tourney_fin_commit              0
singles_winner_name             0
singles_winner_player_slug      0
singles_winner_player_id        0
doubles_winner_1_name           0
doubles_winner_1_player_slug    0
doubles_winner_1_player_id      0
doubles_winner_2_name           0
doubles_winner_2_player_slug    0
doubles_winner_2_player_id      0
dtype: int64

In [27]:
# keeping the dataframe without missing values

tournaments = tournaments_missing.copy()

#### Solving the currency problem:

In [28]:
# checking the different currencies present in the dataset

tournaments['currency'].value_counts()

USD    325
EUR    315
AUD     10
GBP     10
Name: currency, dtype: int64

In [29]:
# defining a dataframe with the exchange rate for US Dollars at 12/03/2023, 09:52 UTC
# https://www.google.com/finance/quote/AUD-USD
# https://www.google.com/finance/quote/EUR-USD
# https://www.google.com/finance/quote/GBP-USD
# all prizes will be converted to USD
exchange_rate = pd.DataFrame(data = {'exchange_rate': [1, 1.0646, 0.6583, 1.2034], 'currency': ['USD', 'EUR', 'AUD', 'GBP']})

# merging the tournaments dataframe with the exchange rate dataframe
merged_tournaments = tournaments.merge(exchange_rate, on = 'currency')

# creating a new column in the merged dataframe with the TFC in US dollars, by multiplying the value with the exchange rate
merged_tournaments['tourney_fin_commit_USD'] = merged_tournaments['tourney_fin_commit'] * merged_tournaments['exchange_rate']

# drop the currency and exchange rate columns, as they are no longer needed
merged_tournaments.drop(['currency', 'exchange_rate', 'tourney_fin_commit'], axis = 1, inplace = True)

# sorting by ascending order regarding variable date
merged_tournaments.sort_index(inplace = True)

In [30]:
# keeping the changes for the currencies in the original dataset

tournaments = merged_tournaments.copy()

Also, since we will be working with the geographic location of the tournaments, it is also interesting to know to which geographical region each tournament belongs. Therefore, we will add a column to the dataset with the Region (either, Oceanina, Asia, Europe, North America, south america, or Africa).

In [31]:
regions_code = {
    'Brisbane': 'oceania',
    'Doha': 'asia',
    'Chennai': 'asia',
    'Sydney': 'oceania',
    'Auckland': 'oceania',
    'Johannesburg': 'africa',
    'Santiago': 'south america',
    'San Jose': 'north america',
    'Costa do Sauipe': 'south america',
    'Memphis': 'north america',
    'Buenos Aires': 'south america',
    'Dubai, United Arab Emirates': 'asia',
    'Acapulco, Mexico': 'north america',
    'Delray Beach': 'north america',
    'Indian Wells': 'north america',
    'Miami': 'north america',
    'Houston, United States': 'north america',
    'Newport, United States': 'north america',
    'Atlanta, United States': 'north america',
    'Los Angeles, United States': 'north america',
    'Washington, United States': 'north america',
    'Toronto, Canada': 'north america',
    'Cincinnati, United States': 'north america',
    'New Haven': 'north america',
    'New York': 'north america',
    'Kuala Lumpur': 'asia',
    'Bangkok': 'asia',
    'Beijing, China': 'asia',
    'Tokyo': 'asia',
    'Shanghai, China': 'asia',
    'Moscow, Russia': 'europe',
    'St. Petersburg, Russia': 'europe',
    'London, Great Britain': 'europe',
    'Brisbane, Australia': 'oceania',
    'Doha, Qatar': 'asia',
    'Chennai, India': 'asia',
    'Sydney, Australia': 'oceania',
    'Auckland, New Zealand': 'oceania',
    'Johannesburg, South Africa': 'africa',
    'Santiago, Chile': 'south america',
    'San Jose, United States': 'north america',
    'Costa do Sauipe, Brazil': 'south america',
    'Memphis, United States': 'north america',
    'Buenos Aires, Argentina': 'south america',
    'Delray Beach, United States': 'north america',
    'Indian Wells, United States': 'north america',
    'Miami, United States': 'north america',
    'Montreal, Canada': 'north america',
    'Winston-Salem, United States': 'north america',
    'New York, United States': 'north america',
    'Kuala Lumpur, Malaysia': 'asia',
    'Bangkok, Thailand': 'asia',
    'Tokyo, Japan': 'asia',
    'Vina del Mar, Chile': 'south america',
    'Sao Paulo, Brazil': 'south america',
    'Bogota, Colombia': 'south america',
    'Rio de Janeiro, Brazil': 'south america',
    'New York City, United States': 'north america',
    'Shenzhen, China': 'asia',
    'Quito, Ecuador': 'south america',
    'Los Cabos, Mexico': 'north america',
    'Chengdu, China': 'asia',
    'Milan, Italy': 'europe',
    'Pune, India': 'asia',
    'Cordoba, Argentina': 'south america',
    'Zhuhai, China': 'asia',
    'Melbourne': 'oceania',
    'Melbourne, Australia': 'oceania',
    'Africagreb': 'europe',
    'Rotterdam': 'europe',
    'Marseille, France': 'europe',
    'Casablanca': 'africa',
    'Monte Carlo': 'Europa',
    'Barcelona': 'europe',
    'Rome': 'europe',
    'Munich': 'europe',
    'Estoril': 'europe',
    'Belgrade': 'europe',
    'Madrid': 'europe',
    'Nice': 'europe',
    'Paris': 'europe',
    'Halle': 'europe',
    'Eastbourne': 'europe',
    's-Hertogenbosch': 'europe',
    'Bastad': 'europe',
    'Stuttgart': 'europe',
    'Hamburg': 'europe',
    'Gstaad': 'europe',
    'Umag': 'europe',
    'Metz': 'europe',
    'Bucharest': 'europe',
    'Stockholm': 'europe',
    'Montpellier': 'europe',
    'Vienna': 'europe',
    'Valencia': 'europe',
    'Basel': 'europe',
    'Zagreb': 'europe',
    'Rotterdam': 'europe',
    'Casablanca': 'africa',
    'Monte Carlo': 'europe',
    'Barcelona': 'europe',
    'Estoril': 'europe',
    'Belgrade': 'europe',
    'Rome': 'europe',
    'Kitzbuhel': 'europe',
    'Metz': 'europe',
    'Bucharest': 'europe',
    'Stockholm': 'europe',
    'Valencia': 'europe',
    'Bastad': 'europe',
    'Kitzbuhel': 'europe',
    'Monte-Carlo': 'europe',
    'Oeiras': 'europe',
    'Dusseldorf': 'europe',
    'Istanbul': 'asia',
    'Geneva': 'europe',
    'Nottingham': 'europe',
    'Sofia': 'europe',
    'Marrakech': 'africa',
    'Antwerp': 'europe',
    'Budapest': 'europe',
    'Lyon': 'europe',
    'Antalya': 'asia',
    'Munich, Germany' : 'europe',
    'Madrid, Spain' : 'europe',
    'Nice, France' : 'europe',
    'Paris, France' : 'europe',
    'Halle, Germany' : 'europe',
    'Eastbourne, Great Britain' : 'europe',
    's-Hertogenbosch, Netherlands' : 'europe',
    'Bastad, Sweden' : 'europe',
    'Stuttgart, Germany' : 'europe',
    'Hamburg, Germany' : 'europe',
    'Gstaad, Switzerland' : 'europe',
    'Umag, Croatia' : 'europe',
    'Montpellier, France' : 'europe',
    'Vienna, Austria' : 'europe',
    'Valencia, Switzerland' : 'europe',
    'Basel, Switzerland' : 'europe',
    'Zagreb, Croatia' : 'europe',
    'Rotterdam, Netherlands' : 'europe',
    'Casablanca, Morocco' : 'africa',
    'Monte Carlo, Monaco' : 'europe',
    'Barcelona, Spain' : 'europe',
    'Estoril, Portugal' : 'europe',
    'Belgrade, Serbia' : 'europe',
    'Rome, Italy' : 'europe',
    'Kitzbhel, Austria' : 'europe',
    'Metz, France' : 'europe',
    'Bucharest, Romania' : 'europe',
    'Stockholm, Sweden' : 'europe',
    'Valencia, Spain' : 'europe',
    'B†stad, Sweden' : 'europe',
    'Kitzbuhel, Austria' : 'europe',
    'Monte-Carlo, Monaco' : 'europe',
    'Oeiras, Portugal' : 'europe',
    'Dusseldorf, Germany' : 'europe',
    'Istanbul, Turkey': 'europe',
    'Geneva, Switzerland': 'europe',
    'Nottingham, Great Britain': 'europe',
    'Sofia, Bulgaria': 'europe',
    'Marrakech, Morocco': 'africa',
    'Antwerp, Belgium': 'europe',
    'Budapest, Hungary': 'europe',
    'Lyon, France': 'europe',
    'Antalya, Turkey': 'europe'
}

# creating a new column called 'tourney_region'
tournaments['tourney_region'] = ''

# loop over the rows of the tournaments dataframe and map the country names to Continents
for i, row in tournaments.iterrows():
    region_name = row['tourney_location']
    if region_name in regions_code:
        continent_code = regions_code[region_name]
    else:
        continent_code = 'unknown'  # set the continent as 'unknown' if not found in the dictionary
    tournaments.loc[i, 'tourney_region'] = continent_code

The same happens for the country and city. From the `tourney_location` variable, the city of the tournament will be extracted, and also a column with the country code will be added, because it will be needed for the map visualizations in the dashboard.

In [32]:
# using split method to keep the city name (that is located before the comma) 

tournaments['tourney_city'] = tournaments['tourney_location'].str.split(',').str[0]

In [33]:
# creating a dictionary mapping city names to country codes
country_codes = {
    'Brisbane': 'AU',
    'Doha': 'QA',
    'Chennai': 'IN',
    'Sydney': 'AU',
    'Auckland': 'NZ',
    'Johannesburg': 'ZA',
    'Santiago': 'CL',
    'San Jose': 'CR',
    'Costa do Sauipe': 'BR',
    'Memphis': 'US',
    'Buenos Aires': 'AR',
    'Dubai, United Arab Emirates': 'AE',
    'Acapulco, Mexico': 'MX',
    'Delray Beach': 'US',
    'Indian Wells': 'US',
    'Miami': 'US',
    'Houston, United States': 'US',
    'Newport, United States': 'US',
    'Atlanta, United States': 'US',
    'Los Angeles, United States': 'US',
    'Washington, United States': 'US',
    'Toronto, Canada': 'CA',
    'Cincinnati, United States': 'US',
    'New Haven': 'US',
    'New York': 'US',
    'Kuala Lumpur': 'MY',
    'Bangkok': 'TH',
    'Beijing, China': 'CN',
    'Tokyo': 'JP',
    'Shanghai, China': 'CN',
    'Moscow, Russia': 'RU',
    'St. Petersburg, Russia': 'RU',
    'London, Great Britain': 'GB',
    'Brisbane, Australia': 'AU',
    'Doha, Qatar': 'QA',
    'Chennai, India': 'IN',
    'Sydney, Australia': 'AU',
    'Auckland, New Zealand': 'NZ',
    'Johannesburg, South Africa': 'ZA',
    'Santiago, Chile': 'CL',
    'San Jose, United States': 'CR',
    'Costa do Sauipe, Brazil': 'BR',
    'Memphis, United States': 'US',
    'Buenos Aires, Argentina': 'AR',
    'Delray Beach, United States': 'US',
    'Indian Wells, United States': 'US',
    'Miami, United States': 'US',
    'Montreal, Canada': 'CA',
    'Winston-Salem, United States': 'US',
    'New York, United States': 'US',
    'Kuala Lumpur, Malaysia': 'MY',
    'Bangkok, Thailand': 'TH',
    'Tokyo, Japan': 'JP',
    'Vina del Mar, Chile': 'CL',
    'Sao Paulo, Brazil': 'BR',
    'Bogota, Colombia': 'CO',
    'Rio de Janeiro, Brazil': 'BR',
    'New York City, United States': 'US',
    'Shenzhen, China': 'CN',
    'Quito, Ecuador': 'EC',
    'Los Cabos, Mexico': 'MX',
    'Chengdu, China': 'CN',
    'Milan, Italy': 'IT',
    'Pune, India': 'IN',
    'Cordoba, Argentina': 'AR',
    'Zhuhai, China': 'CN',
    'Melbourne': 'AU',
    'Melbourne, Australia': 'AU',
    'Zagreb': 'HR',
    'Rotterdam': 'NL',
    'Marseille, France': 'FR',
    'Casablanca': 'MA',
    'Monte Carlo': 'MC',
    'Barcelona': 'ES',
    'Rome': 'IT',
    'Munich': 'DE',
    'Estoril': 'PT',
    'Belgrade': 'RS',
    'Madrid': 'ES',
    'Nice': 'FR',
    'Paris': 'FR',
    'Halle': 'DE',
    'Eastbourne': 'GB',
    's-Hertogenbosch': 'NL',
    'Bastad': 'SE',
    'Stuttgart': 'DE',
    'Hamburg': 'DE',
    'Gstaad': 'CH',
    'Umag': 'HR',
    'Metz': 'FR',
    'Bucharest': 'RO',
    'Stockholm': 'SE',
    'Montpellier': 'FR',
    'Vienna': 'AT',
    'Valencia': 'ES',
    'Basel': 'CH',
    'Zagreb': 'HR',
    'Rotterdam': 'NL',
    'Casablanca': 'MA',
    'Monte Carlo': 'MC',
    'Barcelona': 'ES',
    'Estoril': 'PT',
    'Belgrade': 'RS',
    'Rome': 'IT',
    'Kitzbuhel': 'AT',
    'Metz': 'FR',
    'Bucharest': 'RO',
    'Stockholm': 'SE',
    'Valencia': 'ES',
    'Bastad': 'SE',
    'Kitzbuhel': 'AT',
    'Monte-Carlo': 'MC',
    'Oeiras': 'PT',
    'Dusseldorf': 'DE',
    'Istanbul': 'TR',
    'Geneva': 'CH',
    'Nottingham': 'GB',
    'Sofia': 'BG',
    'Marrakech': 'MA',
    'Antwerp': 'BE',
    'Budapest': 'HU',
    'Lyon': 'FR',
    'Antalya': 'TR',
    'Munich, Germany' : 'DE',
    'Madrid, Spain' : 'ES',
    'Nice, France' : 'FR',
    'Paris, France' : 'FR',
    'Halle, Germany' : 'DE',
    'Eastbourne, Great Britain' : 'GB',
    's-Hertogenbosch, Netherlands' : 'NL',
    'Bastad, Sweden' : 'SE',
    'Stuttgart, Germany' : 'DE',
    'Hamburg, Germany' : 'DE',
    'Gstaad, Switzerland' : 'CH',
    'Umag, Croatia' : 'HR',
    'Montpellier, France' : 'FR',
    'Vienna, Austria' : 'AT',
    'Valencia, Switzerland' : 'ES',
    'Basel, Switzerland' : 'CH',
    'Zagreb, Croatia' : 'HR',
    'Rotterdam, Netherlands' : 'NL',
    'Casablanca, Morocco' : 'MA',
    'Monte Carlo, Monaco' : 'MC',
    'Barcelona, Spain' : 'ES',
    'Estoril, Portugal' : 'PT',
    'Belgrade, Serbia' : 'RS',
    'Rome, Italy' : 'IT',
    'Kitzbhel, Austria' : 'AT',
    'Metz, France' : 'FR',
    'Bucharest, Romania' : 'RO',
    'Stockholm, Sweden' : 'SE',
    'Valencia, Spain' : 'ES',
    'B†stad, Sweden' : 'SE',
    'Kitzbuhel, Austria' : 'AT',
    'Monte-Carlo, Monaco' : 'MC',
    'Oeiras, Portugal' : 'PT',
    'Dusseldorf, Germany' : 'DE',
    'Istanbul, Turkey': 'TR',
    'Geneva, Switzerland': 'CH',
    'Nottingham, Great Britain': 'GB',
    'Sofia, Bulgaria': 'BG',
    'Marrakech, Morocco': 'MA',
    'Antwerp, Belgium': 'BE',
    'Budapest, Hungary': 'HU',
    'Lyon, France': 'FR',
    'Antalya, Turkey': 'TR'
}

# creating a new column called 'country_code
tournaments['country_code'] = ''

# loop over the rows of the data frame and map the country names to country codes
for i, row in tournaments.iterrows():
    country_name = row['tourney_location']
    if country_name in country_codes:
        country_code = country_codes[country_name]
    else:
        country_code = 'unknown'  # setting the country code as 'unknown' if not found in the dictionary
    tournaments.loc[i, 'country_code'] = country_code

Also, for the map, the coordinates of the cities will be needed. Therefore, new columns with the latitude and longitude will also be added. 

In [34]:
# creating empty columns for latitude and longitude
tournaments['latitude'] = ""
tournaments['longitude'] = ""

# iterating through the rows of the dataframe
for i, row in tournaments.iterrows():
    # geting the city name from the 'city' column and convert to lowercase
    city = row['tourney_city']
    code = row['country_code']
    try:
        # using the CityCoordinator object to get the coordinates for the city
        result = c.get_city(city_name = city, country_code_iso = code)

        # extracting the latitude and longitude from the result and add to the dataframe
        tournaments.at[i, 'latitude'] = result['location']['lat']
        tournaments.at[i, 'longitude'] = result['location']['lon']
    except:
        # if the city name is not found, set the latitude and longitude to NaN
        tournaments.at[i, 'latitude'] = float('nan')
        tournaments.at[i, 'longitude'] = float('nan')

In [35]:
# there are some tournaments without the latitude and longitude because the cities' names are different in the dataset and in the CityCoordinator mapper

falta = tournaments[tournaments['latitude'].isna()]
falta.groupby('tourney_city')['tourney_region', 'country_code', 'latitude', 'longitude'].agg('first')

C:\Users\beatr\AppData\Local\Temp\ipykernel_33528\917297412.py:4: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  falta.groupby('tourney_city')['tourney_region', 'country_code', 'latitude', 'longitude'].agg('first')


tourney_region country_code latitude longitude
tourney_city                                                  
Acapulco         north america           MX     None      None
Antwerp                 europe           BE     None      None
Bastad                  europe           SE     None      None
Bogota           south america           CO     None      None
B†stad                  europe           SE     None      None
Cordoba          south america           AR     None      None
Costa do Sauipe  south america           BR     None      None
Dusseldorf              europe           DE     None      None
Geneva                  europe           CH     None      None
Kitzbhel                europe           AT     None      None
Kitzbuhel               europe           AT     None      None
Los Cabos        north america           MX     None      None
Marrakech               africa           MA     None      None
Monte Carlo             europe           MC     None      None
Montreal         north america           CA     None      None
New York         north america           US     None      None
San Jose         north america           CR     None      None
Sao Paulo        south america           BR     None      None
St. Petersburg          europe           RU     None      None
Vina del Mar     south america           CL     None      None
s-Hertogenbosch         europe           NL     None      None

In [36]:
# dictionary with the right cities' names
new_cities = {'Acapulco': 'Acapulco de Juárez',
              'Antwerp': 'Antwerpen',
              'Bastad': 'Båstad',
              'Bogota': 'Bogotá',
              'B†stad': 'Båstad',
              'Cordoba': 'Córdoba',
              'Costa do Sauipe': 'Mata de São João',
              'Dusseldorf': 'Düsseldorf',
              'Geneva': 'Genève',
              'Kitzbhel': 'Kitzbühel',
              'Kitzbuhel': 'Kitzbühel',
              'Los Cabos': 'Cabo San Lucas',
              'Marrakech': 'Marrakesh',
              'Monte Carlo': 'Monte-Carlo',
              'Montreal': 'Montréal',
              'New York': 'New York City',
              'San Jose': 'San José',
              'Sao Paulo': 'São Paulo',
              'St. Petersburg': 'Saint Petersburg',
              'Vina del Mar': 'Viña del Mar',
              's-Hertogenbosch': '\'s-Hertogenbosch'
              }

# replacing the cities' names
tournaments['tourney_city'] = tournaments['tourney_city'].replace(new_cities)

# assigning again the latitude and longitude
# iterating through the rows of the dataframe
for i, row in tournaments.iterrows():
    # geting the city name from the 'city' column and convert to lowercase
    city = row['tourney_city']
    code = row['country_code']
    try:
        # using the CityCoordinator object to get the coordinates for the city
        result = c.get_city(city_name = city, country_code_iso = code)

        # extracting the latitude and longitude from the result and add to the dataframe
        tournaments.at[i, 'latitude'] = result['location']['lat']
        tournaments.at[i, 'longitude'] = result['location']['lon']
    except:
        # if the city name is not found, set the latitude and longitude to NaN
        tournaments.at[i, 'latitude'] = float('nan')
        tournaments.at[i, 'longitude'] = float('nan')

In [37]:
tournaments.T

0                       1    \
tourney_year_id                          2010-339                2010-451   
tourney_order                                   1                       2   
tourney_type                              ATP 250                 ATP 250   
tourney_name                             Brisbane                    Doha   
tourney_id                                    339                     451   
tourney_slug                             brisbane                    doha   
tourney_location                         Brisbane                    Doha   
tourney_date                  2010-01-03 00:00:00     2010-01-04 00:00:00   
year                                         2010                    2010   
tourney_singles_draw                           32                      32   
tourney_doubles_draw                           16                      16   
tourney_conditions                        Outdoor                 Outdoor   
tourney_surface                              Hard                    Hard   
singles_winner_name                  Andy Roddick       Nikolay Davydenko   
singles_winner_player_slug           andy-roddick       nikolay-davydenko   
singles_winner_player_id                     r485                    d402   
doubles_winner_1_name               Jeremy Chardy  Guillermo Garcia-Lopez   
doubles_winner_1_player_slug        jeremy-chardy  guillermo-garcia-lopez   
doubles_winner_1_player_id                   ca12                    g476   
doubles_winner_2_name                Marc Gicquel         Albert Montanes   
doubles_winner_2_player_slug         marc-gicquel         albert-montanes   
doubles_winner_2_player_id                   g436                    m824   
tourney_fin_commit_USD                   424250.0               1110250.0   
tourney_region                            oceania                    asia   
tourney_city                             Brisbane                    Doha   
country_code                                   AU                      QA   
latitude                                -27.46794                25.28545   
longitude                               153.02809                51.53096   

                                              2                    3    \
tourney_year_id                          2010-891             2010-338   
tourney_order                                   3                    4   
tourney_type                              ATP 250              ATP 250   
tourney_name                              Chennai               Sydney   
tourney_id                                    891                  338   
tourney_slug                              chennai               sydney   
tourney_location                          Chennai               Sydney   
tourney_date                  2010-01-04 00:00:00  2010-01-11 00:00:00   
year                                         2010                 2010   
tourney_singles_draw                           32                   28   
tourney_doubles_draw                           16                   16   
tourney_conditions                        Outdoor              Outdoor   
tourney_surface                              Hard                 Hard   
singles_winner_name                   Marin Cilic     Marcos Baghdatis   
singles_winner_player_slug            marin-cilic     marcos-baghdatis   
singles_winner_player_id                     c977                 b837   
doubles_winner_1_name           Marcel Granollers        Daniel Nestor   
doubles_winner_1_player_slug    marcel-granollers        daniel-nestor   
doubles_winner_1_player_id                   g710                 n210   
doubles_winner_2_name            Santiago Ventura       Nenad Zimonjic   
doubles_winner_2_player_slug     santiago-ventura       nenad-zimonjic   
doubles_winner_2_player_id                   v251                 z072   
tourney_fin_commit_USD                   450000.0             424250.0   
tourney_region                      

After starting constructing of the dashboard, we noticed that it was being too slow, maybe due to the high number of features and observations in the datasets. Therefore, we decided to drop the variables and observations that were not needed for the analysis.

In [38]:
tournaments.drop(columns = ['tourney_year_id', 'tourney_order', 'tourney_id', 'tourney_slug', 'tourney_date', 'tourney_singles_draw', 'tourney_doubles_draw', 'singles_winner_player_slug', 'singles_winner_player_id', 'doubles_winner_1_player_slug', 'doubles_winner_1_player_id', 'doubles_winner_2_player_slug', 'doubles_winner_2_player_id'], inplace = True)
tournaments.T

0                       1    \
tourney_type                  ATP 250                 ATP 250   
tourney_name                 Brisbane                    Doha   
tourney_location             Brisbane                    Doha   
year                             2010                    2010   
tourney_conditions            Outdoor                 Outdoor   
tourney_surface                  Hard                    Hard   
singles_winner_name      Andy Roddick       Nikolay Davydenko   
doubles_winner_1_name   Jeremy Chardy  Guillermo Garcia-Lopez   
doubles_winner_2_name    Marc Gicquel         Albert Montanes   
tourney_fin_commit_USD       424250.0               1110250.0   
tourney_region                oceania                    asia   
tourney_city                 Brisbane                    Doha   
country_code                       AU                      QA   
latitude                    -27.46794                25.28545   
longitude                   153.02809                51.53096   

                                      2                 3               4    \
tourney_type                      ATP 250           ATP 250         ATP 250   
tourney_name                      Chennai            Sydney        Auckland   
tourney_location                  Chennai            Sydney        Auckland   
year                                 2010              2010            2010   
tourney_conditions                Outdoor           Outdoor         Outdoor   
tourney_surface                      Hard              Hard            Hard   
singles_winner_name           Marin Cilic  Marcos Baghdatis      John Isner   
doubles_winner_1_name   Marcel Granollers     Daniel Nestor  Marcus Daniell   
doubles_winner_2_name    Santiago Ventura    Nenad Zimonjic     Horia Tecau   
tourney_fin_commit_USD           450000.0          424250.0        407250.0   
tourney_region                       asia           oceania         oceania   
tourney_city                      Chennai            Sydney        Auckland   
country_code                           IN                AU              NZ   
latitude                         13.08784         -33.86785       -36.84853   
longitude                        80.27847         151.20732       174.76349   

                                         5                6    \
tourney_type                         ATP 250          ATP 250   
tourney_name                    Johannesburg         Santiago   
tourney_location                Johannesburg         Santiago   
year                                    2010             2010   
tourney_conditions                   Outdoor          Outdoor   
tourney_surface                         Hard             Clay   
singles_winner_name          Feliciano Lopez  Thomaz Bellucci   
doubles_winner_1_name          Rohan Bopanna     Lukasz Kubot   
doubles_winner_2_name   Aisam-Ul-Haq Qureshi    Oliver Marach   
tourney_fin_commit_USD              500000.0         450000.0   
tourney_region                        africa    south america   
tourney_city                    Johannesburg         Santiago   
country_code                              ZA               CL   
latitude                           -26.20227        -33.45694   
longitude                           28.04363        -70.64827   

                                      7                    8              9    \
tourney_type                      ATP 250              ATP 250        ATP 500   
tourney_name                     San Jose      Costa do Sauipe        Memphis   
tourney_location                 San Jose      Costa do Sauipe        Memphis   
year                                 2010                 2010           2010   
tourney_conditions                 Indoor              Outdoor         Indoor   
tourney_surface                      Hard                 Clay           Hard   
singles_winner_name     Fernando Verdasco  Juan Carlos Ferrero    Sam Querrey   
doubles_winner_1_name          Mardy Fi

<a id = "understanding-preparation-match-scores"></a>

## 3. Data understanding and preparation - Match Scores dataset

[Back to TOC](#toc)

In [39]:
match_scores.T

0      \
tourney_year_id                                                  2010-339   
tourney_order                                                           1   
tourney_name                                                     Brisbane   
tourney_slug                                                     brisbane   
tourney_url_suffix           /en/scores/archive/brisbane/339/2010/results   
start_date                                                     2010.01.03   
start_year                                                         2010.0   
start_month                                                           1.0   
start_day                                                             3.0   
end_date                                                       2010.01.10   
end_year                                                           2010.0   
end_month                                                             1.0   
end_day                                                              10.0   
currency                                                              USD   
prize_money                                                      372500.0   
match_index                                                         MS001   
tourney_round_name                                                 Finals   
round_order                                                             1   
match_order                                                             1   
winner_name                                                  Andy Roddick   
winner_player_id                                                     r485   
winner_slug                                                  andy-roddick   
loser_name                                                 Radek Stepanek   
loser_player_id                                                      s694   
loser_slug                                                 radek-stepanek   
winner_seed                                                             1   
loser_seed                                                              2   
match_score_tiebreaks                                         76(2) 76(7)   
winner_sets_won                                                       2.0   
loser_sets_won                                                        0.0   
winner_games_won                                                     14.0   
loser_games_won                                                      12.0   
winner_tiebreaks_won                                                  2.0   
loser_tiebreaks_won                                                   0.0   
match_id                                     2010-339-MS001-8-1-r485-s694   
match_stats_url_suffix  /en/scores/2010/339/MS001/match-stats?isLive=F...   

                                                                    1      \
tourney_year_id                                                  2010-339   
tourney_order                                                           1   
tourney_name                                                     Brisbane   
tourney_slug                                                     brisbane   
tourney_url_suffix           /en/scores/archive/brisbane/339/2010/results   
start_date                                                     2010.01.03   
start_year                                                         2010.0   
start_month                                                           1.0   
start_day                                                             3.0   
end_date                                                       2010.01.10   
end_year                                                           2010.0   
end_month                                                             1.0   
end_day                                                              10.0   
currency                                                              USD   
prize_money                                                    

**Variables**:

- `tourney_year_id`
- `tourney_order`: in terms of the calendar.
- `tourney_name`
- `tourney_slug`
- `tourney_url_suffix`
- `start_date`: of the tournament.
- `start_year`
- `start_month`
- `start_day`
- `end_date`: of the tournament.
- `end_year`
- `end_month`
- `end_day`
- `currency`
- `prize_money`
- `match_index`
- `tourney_round_name`: different rounds of matches played in the tournament, like: *qualifying rounds*, *first round* (round of 64 or round of 32, for example), *second round*, *third round*, *quarterfinals*, *semifinals*, *finals*, etc.
- `round_order`: refers to the order of the round, for example Finals would have *round_order* 1, semifinals would have *round_order* 2 and quarterfinals would have *round_order* 3. 
- `match_order`: refers to the order of the game within the round, for example, the first game in the semifinals would have *match_order* 1, and the second game would have *match_order* 2, while, in the same tournament, the first game in the quarterfinals would have *match_order* 1, the second game would have *match_order* 2, the third game would have *match_order* 3, and so on.
- `winner_name`
- `winner_player_id`
- `winner_slug`
- `loser_name`
- `loser_player_id`
- `loser_slug`
- `winner_seed`: a seed refers to a player who is ranked among the top players in the tournament and is given a predetermined ranking that is used to determine their position in the tournament draw. The seeding process involves assigning a number to each of the top-ranked players in the tournament based on their world ranking. So, this variable stores the seed of the player who won the game.
- `loser_seed`: while this variable stores the seed of the player who lost the game.
- `match_score_tiebreaks`: total score (including tiebreaks, if any)
- `winner_sets_won`
- `loser_sets_won`
- `winner_games_won`
- `loser_games_won`
- `winner_tiebreaks_won`
- `loser_tiebreaks_won`
- `match_id`
- `match_stats_url_suffix`


In [40]:
# checking the shape of the dataset

match_scores.shape

(42827, 36)

#### Data types:

In [41]:
# checking the types of the variables, as well as the number of non-null observations in each variable

match_scores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42827 entries, 0 to 42826
Data columns (total 36 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   tourney_year_id         42827 non-null  object 
 1   tourney_order           42827 non-null  int64  
 2   tourney_name            42827 non-null  object 
 3   tourney_slug            42827 non-null  object 
 4   tourney_url_suffix      42827 non-null  object 
 5   start_date              42655 non-null  object 
 6   start_year              42655 non-null  float64
 7   start_month             42655 non-null  float64
 8   start_day               42655 non-null  float64
 9   end_date                42655 non-null  object 
 10  end_year                42655 non-null  float64
 11  end_month               42655 non-null  float64
 12  end_day                 42655 non-null  float64
 13  currency                42655 non-null  object 
 14  prize_money             42655 non-null

Some games have the information regarding the start and end of the tournament missing, and also regarding the `prize_money` of that specific game. It is worth noticing that `start_date` and `end_date` are stored as a string and not as a date. There are also missing variables in variable `match_index` and the seeds, which is normal, since the seed of a player in a tournament refers to their ranking or positioning in the tournament draw, which is determined by their ranking in the ATP, and usually the tournaments seed only 8 or 16 players. There are also other statistics that are missing sometimes, like the number of sets, the number of games, and the number of tiebreaks. Also, the url for the statistics is missing in some cases.

In [42]:
# storing correctly the variables regarding dates

match_scores['start_date'] = pd.to_datetime(match_scores['start_date'], format = '%Y.%m.%d')
match_scores['end_date'] = pd.to_datetime(match_scores['end_date'], format = '%Y.%m.%d')

#### Descriptive statistics:

In [43]:
match_scores.describe().T

count          mean           std     min       25%  \
tourney_order         42827.0  3.295858e+01  1.826405e+01     1.0      19.0   
start_year            42655.0  2.014336e+03  2.850391e+00  2010.0    2012.0   
start_month           42655.0  5.498160e+00  2.952809e+00     1.0       3.0   
start_day             42655.0  1.684567e+01  8.582518e+00     1.0      10.0   
end_year              42655.0  2.014348e+03  2.851810e+00  2010.0    2012.0   
end_month             42655.0  5.663627e+00  2.982104e+00     1.0       3.0   
end_day               42655.0  1.547279e+01  8.703418e+00     1.0       8.0   
prize_money           42655.0  4.728724e+06  6.543085e+06     0.0  501345.0   
round_order           42827.0  5.952016e+00  2.055415e+00     1.0       5.0   
match_order           42827.0  1.013181e+01  1.191788e+01     1.0       3.0   
winner_sets_won       42605.0  2.105410e+00  3.570580e-01     0.0       2.0   
loser_sets_won        42605.0  3.857294e-01  5.325505e-01     0.0       0.0   
winner_games_won      42605.0  1.458587e+01  3.681029e+00     0.0      12.0   
loser_games_won       42605.0  9.630231e+00  4.797228e+00     0.0       6.0   
winner_tiebreaks_won  42605.0  3.274498e-01  5.410730e-01     0.0       0.0   
loser_tiebreaks_won   42605.0  8.846380e-02  2.876670e-01     0.0       0.0   

                            50%        75%         max  
tourney_order              33.0       49.0        69.0  
start_year               2014.0     2017.0      2019.0  
start_month                 6.0        8.0        12.0  
start_day                  18.0       24.0        31.0  
end_year                 2014.0     2017.0      2019.0  
end_month                   6.0        8.0        11.0  
end_day                    15.0       23.0        31.0  
prize_money           1404300.0  6196000.0  29687000.0  
round_order                 6.0        7.0        10.0  
match_order                 6.0       12.0        64.0  
winner_sets_won             2.0        2.0         3.0  
loser_sets_won              0.0        1.0         2.0  
winner_games_won           13.0       17.0        92.0  
loser_games_won             9.0       13.0        91.0  
winner_tiebreaks_won        0.0        1.0         3.0  
loser_tiebreaks_won         0.0        0.0         2.0

In [44]:
match_scores.describe(include = ['O']).T

count unique  \
tourney_year_id         42827    664   
tourney_name            42827     95   
tourney_slug            42827     95   
tourney_url_suffix      42827    664   
currency                42655      4   
match_index             42447    252   
tourney_round_name      42827     13   
winner_name             42827   1195   
winner_player_id        42827   1195   
winner_slug             42827   1195   
loser_name              42827   2122   
loser_player_id         42827   2125   
loser_slug              42827   2122   
winner_seed             25831     62   
loser_seed              20528     61   
match_score_tiebreaks   42827   6544   
match_id                42827  42827   
match_stats_url_suffix  42447  42447   

                                                                      top  \
tourney_year_id                                                  2017-540   
tourney_name                                                Roland Garros   
tourney_slug                                                    wimbledon   
tourney_url_suffix          /en/scores/archive/wimbledon/540/2017/results   
currency                                                              USD   
match_index                                                         MS019   
tourney_round_name                                   1st Round Qualifying   
winner_name                                                Novak Djokovic   
winner_player_id                                                     d643   
winner_slug                                                novak-djokovic   
loser_name                                           Albert Ramos-Vinolas   
loser_player_id                                                      r772   
loser_slug                                           albert-ramos-vinolas   
winner_seed                                                             1   
loser_seed                                                             WC   
match_score_tiebreaks                                               63 64   
match_id                                     2010-339-MS001-8-1-r485-s694   
match_stats_url_suffix  /en/scores/2010/339/MS001/match-stats?isLive=F...   

                         freq  
tourney_year_id           239  
tourney_name             2390  
tourney_slug             2390  
tourney_url_suffix        239  
currency                19510  
match_index               661  
tourney_round_name       9596  
winner_name               620  
winner_player_id          620  
winner_slug               620  
loser_name                257  
loser_player_id           257  
loser_slug                257  
winner_seed              2477  
loser_seed               4212  
match_score_tiebreaks    1552  
match_id                    1  
match_stats_url_suffix      1

Regarding these statistics, it can be seen that the mean of sets won by the winner is 2.1, which makes sense as the majority of the tournaments are played at the best of three sets. Also, the average of games won by the winner is 14.6 and the average of games won by the loser is 9.7. The average prize money is 4.7 million for the tournaments. The player that won more games in this dataframe was Novak Djokovic and the player that lost more was Albert Ramos-Vinolas. Regarding the seeds, the majority of winners of games are 1st seed, while the majority of losers are Wild Cards. Wild Cards is a special entry that allows a player or team to participate in a tournament without having to go through the usual qualification process, and are usually granted by the tournament organizers to players or teams who are not eligible for direct entry into the tournament based on their ranking, but who are deemed to be of sufficient quality or interest to enhance the tournament's appeal.

#### Do not make sense for our analysis:

As before, we have URL in the dataset (`tourney_url_suffix`, `match_stats_url_suffix`), that do not make sense for our analysis, therefore will also be deleted. The same happens for the `match_order`, as it is irrelevant to know what were the matches that played before or after in the same round (the only thing that matters is the round).

In [45]:
# dropping the variables as explained before

match_scores.drop(columns = ['tourney_url_suffix', 'match_stats_url_suffix', 'match_order'], inplace = True)

Again, we have columns that have redundant information, particularly the dates columns, as we have two columns for start date and end date, and other 6 columns for the decomposition of these dates (year, month, and day). They are not necessary, so we will delete them.

In [46]:
# dropping the variables as explained above

match_scores.drop(columns = ['start_year', 'start_month', 'start_day', 'end_year', 'end_month', 'end_day'], inplace = True)

In [47]:
match_scores['tourney_name'].unique()

array(['Brisbane', 'Doha', 'Chennai', 'Sydney', 'Auckland',
       'Australian Open', 'Johannesburg', 'Santiago', 'Zagreb',
       'Rotterdam', 'San Jose', 'Costa do Sauipe', 'Memphis', 'Marseille',
       'Buenos Aires', 'Dubai', 'Acapulco', 'Delray Beach',
       'ATP Masters 1000 Indian Wells', 'ATP Masters 1000 Miami',
       'Houston', 'Casablanca', 'ATP Masters 1000 Monte Carlo',
       'Barcelona', 'ATP Masters 1000 Rome', 'Munich', 'Estoril',
       'Belgrade', 'ATP Masters 1000 Madrid', 'World Team Championship',
       'Nice', 'Roland Garros', 'Halle', "London / Queen's Club",
       'Eastbourne', 's-Hertogenbosch', 'Wimbledon', 'Newport', 'Bastad',
       'Stuttgart', 'Hamburg', 'Atlanta', 'Gstaad', 'Los Angeles', 'Umag',
       'Washington', 'ATP Masters 1000 Canada',
       'ATP Masters 1000 Cincinnati', 'New Haven', 'US Open', 'Metz',
       'Bucharest', 'Kuala Lumpur', 'Bangkok', 'Beijing', 'Tokyo',
       'ATP Masters 1000 Shanghai', 'Moscow', 'Stockholm',
       'St. P

As it can be seen, there are tournaments in this data that are not suitable for our analysis. As explained before, we are not considering Olympics nor World Team Championship. So these observations will be deleted.

In [48]:
# droping the observations that refer to the tournaments mentioned above

match_scores = match_scores[match_scores['tourney_name'] != 'London Olympics']
match_scores = match_scores[match_scores['tourney_name'] != 'World Team Championship']
match_scores = match_scores[match_scores['tourney_name'] != 'Rio de Janeiro Olympic Games']

#### Missing values:

In [49]:
# creating a copy to solve the problems with missing values

match_scores_missing = match_scores.copy()

In [50]:
# replacing other types of missing values not recognized by pandas with NaN and checking again the number of missing values

match_scores_missing.replace(missing_values, np.nan, inplace = True)
match_scores_missing.isna().sum()

tourney_year_id              0
tourney_order                0
tourney_name                 0
tourney_slug                 0
start_date                 172
end_date                   172
currency                   172
prize_money                172
match_index                300
tourney_round_name           0
round_order                  0
winner_name                  0
winner_player_id             0
winner_slug                  0
loser_name                   0
loser_player_id              0
loser_slug                   0
winner_seed              16872
loser_seed               22131
match_score_tiebreaks        0
winner_sets_won            221
loser_sets_won             221
winner_games_won           221
loser_games_won            221
winner_tiebreaks_won       221
loser_tiebreaks_won        221
match_id                     0
dtype: int64

In [51]:
# seeing rows with NaNs

match_scores_nans_index = match_scores_missing.isna().any(axis = 1)
match_scores_missing[match_scores_nans_index].T

3      \
tourney_year_id                            2010-339   
tourney_order                                     1   
tourney_name                               Brisbane   
tourney_slug                               brisbane   
start_date                      2010-01-03 00:00:00   
end_date                        2010-01-10 00:00:00   
currency                                        USD   
prize_money                                372500.0   
match_index                                   MS004   
tourney_round_name                   Quarter-Finals   
round_order                                       3   
winner_name                            Andy Roddick   
winner_player_id                               r485   
winner_slug                            andy-roddick   
loser_name                          Richard Gasquet   
loser_player_id                                g628   
loser_slug                          richard-gasquet   
winner_seed                                       1   
loser_seed                                      NaN   
match_score_tiebreaks                      63 76(5)   
winner_sets_won                                 2.0   
loser_sets_won                                  0.0   
winner_games_won                               13.0   
loser_games_won                                 9.0   
winner_tiebreaks_won                            1.0   
loser_tiebreaks_won                             0.0   
match_id               2010-339-MS004-6-4-r485-g628   

                                              4      \
tourney_year_id                            2010-339   
tourney_order                                     1   
tourney_name                               Brisbane   
tourney_slug                               brisbane   
start_date                      2010-01-03 00:00:00   
end_date                        2010-01-10 00:00:00   
currency                                        USD   
prize_money                                372500.0   
match_index                                   MS007   
tourney_round_name                   Quarter-Finals   
round_order                                       3   
winner_name                          Radek Stepanek   
winner_player_id                               s694   
winner_slug                          radek-stepanek   
loser_name                            Wayne Odesnik   
loser_player_id                                o234   
loser_slug                            wayne-odesnik   
winner_seed                                       2   
loser_seed                                      NaN   
match_score_tiebreaks                      76(2) 61   
winner_sets_won                                 2.0   
loser_sets_won                                  0.0   
winner_games_won                               13.0   
loser_games_won                                 7.0   
winner_tiebreaks_won                            1.0   
loser_tiebreaks_won                             0.0   
match_id               2010-339-MS007-6-3-s694-o234   

                                              5      \
tourney_year_id                            2010-339   
tourney_order                                     1   
tourney_name                               Brisbane   
tourney_slug                               brisbane   
start_date                      2010-01-03 00:00:00   
end_date                        2010-01-10 00:00:00   
currency                                        USD   
prize_money                                372500.0   
match_index                                   MS006   
tourney_round_name                   Quarter-Finals   
round_order                                       3   
winner_name                            Gael Monfils   
winner_player_id                               mc65   
winner_slug                            gael-monfils   
loser_name                              James Blake   
loser_player_id                                b676   
loser_slug                   

In [52]:
# seeing missing values in the dates variables

match_scores_missing[match_scores_missing['start_date'].isna()]

tourney_year_id  tourney_order tourney_name tourney_slug start_date  \
838          2010-402             13      Memphis      memphis        NaT   
839          2010-402             13      Memphis      memphis        NaT   
840          2010-402             13      Memphis      memphis        NaT   
841          2010-402             13      Memphis      memphis        NaT   
842          2010-402             13      Memphis      memphis        NaT   
...               ...            ...          ...          ...        ...   
14497        2013-402             13      Memphis      memphis        NaT   
14498        2013-402             13      Memphis      memphis        NaT   
14499        2013-402             13      Memphis      memphis        NaT   
14500        2013-402             13      Memphis      memphis        NaT   
14501        2013-402             13      Memphis      memphis        NaT   

      end_date currency  prize_money match_index    tourney_round_name  ...  \
838        NaT      NaN          NaN       MS001                Finals  ...   
839        NaT      NaN          NaN       MS003           Semi-Finals  ...   
840        NaT      NaN          NaN       MS002           Semi-Finals  ...   
841        NaT      NaN          NaN       MS004        Quarter-Finals  ...   
842        NaT      NaN          NaN       MS005        Quarter-Finals  ...   
...        ...      ...          ...         ...                   ...  ...   
14497      NaT      NaN          NaN       QS014  1st Round Qualifying  ...   
14498      NaT      NaN          NaN       QS013  1st Round Qualifying  ...   
14499      NaT      NaN          NaN       QS011  1st Round Qualifying  ...   
14500      NaT      NaN          NaN       QS015  1st Round Qualifying  ...   
14501      NaT      NaN          NaN       QS009  1st Round Qualifying  ...   

       winner_seed loser_seed match_score_tiebreaks winner_sets_won  \
838              8          6        67(3) 76(5) 63             2.0   
839              6        NaN              75 46 63             2.0   
840              8        NaN                 63 64             2.0   
841              8          1              75 36 61             2.0   
842            NaN          5           36 63 76(3)             2.0   
...            ...        ...                   ...             ...   
14497            4         WC                 63 64             2.0   
14498            5         WC                 75 61             2.0   
14499          NaN          6              64 76(3)             2.0   
14500            7        NaN        76(4) 26 76(4)             2.0   
14501          NaN          8                 62 61             2.0   

      loser_sets_won winner_games_won loser_games_won winner_tiebreaks_won  \
838              1.0             19.0            16.0                  1.0   
839              1.0             17.0            14.0                  0.0   
840              0.0             12.0             7.0                  0.0   
841              1.0             16.0            12.0                  0.0   
842              1.0             16.0            15.0                  1.0   
...              ...              ...             ...                  ...   
14497            0.0             12.0             7.0                  0.0   
14498            0.0             13.0             6.0                  0.0   
14499            0.0             13.0            10.0                  1.0   
14500            1.0             16.0            18.0                  2.0   
14501            0.0             12.0             3.0                  0.0   

      loser_tiebreaks_won                      match_id  
838                   1.0  2010-402-MS001-7-1-q927-i186  
839                   0.0  2010-402-MS003-6-2-i186-p624  
840                   0.0  2010-402-MS002-6-1-q927-g858  
841                   0.0  2010-402-MS004-5-4-q927-r485  
842                   0.0  2010-402-MS005-5-3-g858-b

We can manually inpute the values that are missing regarding the dates, by seraching on the internet what were the actual dates of the tournaments (they are only 4 tournaments).

In [53]:
# from https://en.wikipedia.org/wiki/2010_Regions_Morgan_Keegan_Championships_and_the_Cellular_South_Cup
match_scores_missing.loc[match_scores_missing['tourney_year_id'] == '2010-402', 'start_date'] = pd.to_datetime('2010-02-13')
match_scores_missing.loc[match_scores_missing['tourney_year_id'] == '2010-402', 'end_date'] = pd.to_datetime('2010-02-21')

# from https://en.wikipedia.org/wiki/2011_Regions_Morgan_Keegan_Championships_and_the_Cellular_South_Cup
match_scores_missing.loc[match_scores_missing['tourney_year_id'] == '2011-402', 'start_date'] = pd.to_datetime('2011-02-13')
match_scores_missing.loc[match_scores_missing['tourney_year_id'] == '2011-402', 'end_date'] = pd.to_datetime('2011-02-20')

# from https://en.wikipedia.org/wiki/2012_Regions_Morgan_Keegan_Championships_and_Memphis_International
match_scores_missing.loc[match_scores_missing['tourney_year_id'] == '2012-402', 'start_date'] = pd.to_datetime('2012-02-17')
match_scores_missing.loc[match_scores_missing['tourney_year_id'] == '2012-402', 'end_date'] = pd.to_datetime('2012-02-26')

# from https://en.wikipedia.org/wiki/2013_U.S._National_Indoor_Tennis_Championships
match_scores_missing.loc[match_scores_missing['tourney_year_id'] == '2013-402', 'start_date'] = pd.to_datetime('2013-02-18')
match_scores_missing.loc[match_scores_missing['tourney_year_id'] == '2013-402', 'end_date'] = pd.to_datetime('2013-02-24')

In [54]:
# seeing missing values in the doubles winner variable

match_scores_missing[match_scores_missing['prize_money'].isna()]

tourney_year_id  tourney_order tourney_name tourney_slug start_date  \
838          2010-402             13      Memphis      memphis 2010-02-13   
839          2010-402             13      Memphis      memphis 2010-02-13   
840          2010-402             13      Memphis      memphis 2010-02-13   
841          2010-402             13      Memphis      memphis 2010-02-13   
842          2010-402             13      Memphis      memphis 2010-02-13   
...               ...            ...          ...          ...        ...   
14497        2013-402             13      Memphis      memphis 2013-02-18   
14498        2013-402             13      Memphis      memphis 2013-02-18   
14499        2013-402             13      Memphis      memphis 2013-02-18   
14500        2013-402             13      Memphis      memphis 2013-02-18   
14501        2013-402             13      Memphis      memphis 2013-02-18   

        end_date currency  prize_money match_index    tourney_round_name  ...  \
838   2010-02-21      NaN          NaN       MS001                Finals  ...   
839   2010-02-21      NaN          NaN       MS003           Semi-Finals  ...   
840   2010-02-21      NaN          NaN       MS002           Semi-Finals  ...   
841   2010-02-21      NaN          NaN       MS004        Quarter-Finals  ...   
842   2010-02-21      NaN          NaN       MS005        Quarter-Finals  ...   
...          ...      ...          ...         ...                   ...  ...   
14497 2013-02-24      NaN          NaN       QS014  1st Round Qualifying  ...   
14498 2013-02-24      NaN          NaN       QS013  1st Round Qualifying  ...   
14499 2013-02-24      NaN          NaN       QS011  1st Round Qualifying  ...   
14500 2013-02-24      NaN          NaN       QS015  1st Round Qualifying  ...   
14501 2013-02-24      NaN          NaN       QS009  1st Round Qualifying  ...   

       winner_seed loser_seed match_score_tiebreaks winner_sets_won  \
838              8          6        67(3) 76(5) 63             2.0   
839              6        NaN              75 46 63             2.0   
840              8        NaN                 63 64             2.0   
841              8          1              75 36 61             2.0   
842            NaN          5           36 63 76(3)             2.0   
...            ...        ...                   ...             ...   
14497            4         WC                 63 64             2.0   
14498            5         WC                 75 61             2.0   
14499          NaN          6              64 76(3)             2.0   
14500            7        NaN        76(4) 26 76(4)             2.0   
14501          NaN          8                 62 61             2.0   

      loser_sets_won winner_games_won loser_games_won winner_tiebreaks_won  \
838              1.0             19.0            16.0                  1.0   
839              1.0             17.0            14.0                  0.0   
840              0.0             12.0             7.0                  0.0   
841              1.0             16.0            12.0                  0.0   
842              1.0             16.0            15.0                  1.0   
...              ...              ...             ...                  ...   
14497            0.0             12.0             7.0                  0.0   
14498            0.0             13.0             6.0                  0.0   
14499            0.0             13.0            10.0                  1.0   
14500            1.0             16.0            18.0                  2.0   
14501            0.0             12.0             3.0                  0.0   

      loser_tiebreaks_won                      match_id  
838                   1.0  2010-402-MS001-7-1-q927-i186  
839                   0.0  2010-402-MS003-6-2-i186-p624  
840                   0.0  2010-402-MS002-6-1-q927-g858  
841                   0.0  2010-402-MS004-5-4-q927-r485  
842                   0.0  2

After a search it was possible to impute the prize money for these tournaments. And since they are US tournaments, the currency of the prize is 'USD'.

In [55]:
# https://en.wikipedia.org/wiki/2010_Regions_Morgan_Keegan_Championships_and_the_Cellular_South_Cup
match_scores_missing.loc[match_scores_missing['tourney_year_id'] == '2010-402', 'prize_money'] = 1226500
# https://www.memphisdailynews.com/news/2011/feb/14/memphis-aces//print
match_scores_missing.loc[match_scores_missing['tourney_year_id'] == '2011-402', 'prize_money'] = 1226500
# https://oncourtadvantage.com/eye-on-the-tour/memphis-open-tennis-2012/
match_scores_missing.loc[match_scores_missing['tourney_year_id'] == '2012-402', 'prize_money'] = 1281500
# https://en.wikipedia.org/wiki/2013_U.S._National_Indoor_Tennis_Championships
match_scores_missing.loc[match_scores_missing['tourney_year_id'] == '2013-402', 'prize_money'] = 1353550

match_scores_missing.loc[match_scores_missing['tourney_year_id'] == '2010-402', 'currency'] = 'USD'
match_scores_missing.loc[match_scores_missing['tourney_year_id'] == '2011-402', 'currency'] = 'USD'
match_scores_missing.loc[match_scores_missing['tourney_year_id'] == '2012-402', 'currency'] = 'USD'
match_scores_missing.loc[match_scores_missing['tourney_year_id'] == '2013-402', 'currency'] = 'USD'

Regarding the missing values on `match_index`, since it is a variable that is not important for our analysis, it will be deleted. 

As for the seeds variables, as explained before, it is normal to have observations with missing values. Therefore the missing values will be imputed with '*not applicable*'.

In [56]:
# dropping the march_index variable
match_scores_missing.drop('match_index', axis = 1, inplace = True)

# inputing the missing values on the seeds variables
match_scores_missing['winner_seed'].fillna('Not applicable', inplace = True)
match_scores_missing['loser_seed'].fillna('Not applicable', inplace = True)

In [57]:
# seeing missing values in the doubles winner variable

match_scores_missing[match_scores_missing['winner_sets_won'].isna()]

tourney_year_id  tourney_order            tourney_name     tourney_slug  \
89           2010-451              2                    Doha             doha   
298          2010-580              6         Australian Open  australian-open   
552         2010-5012              7            Johannesburg     johannesburg   
682          2010-407             10               Rotterdam        rotterdam   
942          2010-506             15            Buenos Aires     buenos-aires   
...               ...            ...                     ...              ...   
42009        2019-560             52                 US Open          us-open   
42404        2019-747             58                 Beijing          beijing   
42692        2019-328             65                   Basel            basel   
42721        2019-328             65                   Basel            basel   
42734        2019-352             66  ATP Masters 1000 Paris            paris   

      start_date   end_date currency  prize_money    tourney_round_name  \
89    2010-01-04 2010-01-09      USD    1024000.0  2nd Round Qualifying   
298   2010-01-18 2010-01-31      AUD   11048640.0           Round of 32   
552   2010-02-01 2010-02-07      USD     442500.0  2nd Round Qualifying   
682   2010-02-08 2010-02-14      EUR    1150000.0        Quarter-Finals   
942   2010-02-15 2010-02-21      USD     475300.0        Quarter-Finals   
...          ...        ...      ...          ...                   ...   
42009 2019-08-26 2019-09-08      USD   28619350.0           Round of 64   
42404 2019-09-30 2019-10-06      USD    3515225.0  1st Round Qualifying   
42692 2019-10-21 2019-10-27      EUR    2082655.0        Quarter-Finals   
42721 2019-10-21 2019-10-27      EUR    2082655.0  2nd Round Qualifying   
42734 2019-10-28 2019-11-03      EUR    5207405.0           Semi-Finals   

       round_order  ...     winner_seed      loser_seed match_score_tiebreaks  \
89               7  ...               2  Not applicable                 (W/O)   
298              5  ...  Not applicable              20                 (W/O)   
552              7  ...               8  Not applicable                 (W/O)   
682              3  ...               1  Not applicable                 (W/O)   
942              3  ...               5  Not applicable                 (W/O)   
...            ...  ...             ...             ...                   ...   
42009            6  ...  Not applicable              12                 (W/O)   
42404            7  ...  Not applicable               3                 (W/O)   
42692            3  ...               1               7                 (W/O)   
42721            6  ...               3               6                 (W/O)   
42734            2  ...  Not applicable               2                 (W/O)   

      winner_sets_won loser_sets_won winner_games_won loser_games_won  \
89                NaN            NaN              NaN             NaN   
298               NaN            NaN              NaN             NaN   
552               NaN            NaN              NaN             NaN   
682               NaN            NaN              NaN             NaN   
942               NaN            NaN              NaN             NaN   
...               ...            ...              ...             ...   
42009             NaN            NaN              NaN             NaN   
42404             NaN            NaN              NaN             NaN   
42692             NaN            NaN              NaN             NaN   
42721             NaN            NaN              NaN             NaN   
42734             NaN            NaN              NaN             NaN   

      winner_tiebreaks_won loser_tiebreaks_won                      match_id  
89                     NaN                 NaN   2010-451-NULL-2-7-b804-l480  
298                    NaN                 NaN   2010-580-NULL-6-4-k540-y061  
552                    NaN                 Na

As it can be seen, the missing values in the tiebreaks, sets, and games statistics are due to the match score: W/O. A walkover occurs when one player wins a match without having to play any points, games, or sets. This can happen when the opponent of a player withdraws from the match before it begins, or is unable to continue playing during the match due to injury, illness, or other reasons. So, the missing values are normal, therefore will be inputed as 0.

In [58]:
# inputing the missing values on the match statistics variables

match_scores_missing.loc[match_scores_missing['winner_sets_won'].isna(), ['winner_sets_won', 'loser_sets_won', 'winner_games_won', 'loser_games_won', 'winner_tiebreaks_won', 'loser_tiebreaks_won']] = 0

In [59]:
# checking that there are no more missing values

match_scores_missing.isna().sum()

tourney_year_id          0
tourney_order            0
tourney_name             0
tourney_slug             0
start_date               0
end_date                 0
currency                 0
prize_money              0
tourney_round_name       0
round_order              0
winner_name              0
winner_player_id         0
winner_slug              0
loser_name               0
loser_player_id          0
loser_slug               0
winner_seed              0
loser_seed               0
match_score_tiebreaks    0
winner_sets_won          0
loser_sets_won           0
winner_games_won         0
loser_games_won          0
winner_tiebreaks_won     0
loser_tiebreaks_won      0
match_id                 0
dtype: int64

In [60]:
# keeping the dataframe without missing values

match_scores = match_scores_missing.copy()

Having the year can be useful, so a new variable called `tourney_year` will be created.

In [61]:
# creating variable 'tourney_year'

match_scores['tourney_year'] = match_scores['tourney_year_id'].str[:4].astype('int32')

Also, since we will need the players that play together the most, a new column will be added, that combines the winner and loser names in alphabetical order.

In [62]:
# creating variable 'pair'

match_scores['pair'] = match_scores.apply(lambda row: '-'.join(sorted([row['winner_name'], row['loser_name']])), axis = 1)

#### Solving the currency problem:

In [63]:
# checking the different currencies present in the dataset

match_scores['currency'].value_counts()

USD    19618
EUR    18223
AUD     2390
GBP     2390
Name: currency, dtype: int64

In [64]:
# using the same dataframe with the exchange rates defined before

# merging the tournaments dataframe with the exchange rate dataframe
merged_match_scores = match_scores.merge(exchange_rate, on = 'currency')

# creating a new column in the merged dataframe with the TFC in US dollars, by multiplying the value with the exchange rate
merged_match_scores['prize_money_USD'] = merged_match_scores['prize_money'] * merged_match_scores['exchange_rate']

# drop the currency and exchange rate columns, as they are no longer needed
merged_match_scores.drop(['currency', 'exchange_rate', 'prize_money'], axis = 1, inplace = True)

# sorting by ascending order regarding variable date
merged_match_scores.sort_index(inplace = True)

In [65]:
# keeping the changes for the currencies in the original dataset

match_scores = merged_match_scores.copy()

In [66]:
match_scores

tourney_year_id  tourney_order tourney_name tourney_slug start_date  \
0            2010-339              1     Brisbane     brisbane 2010-01-03   
1            2010-339              1     Brisbane     brisbane 2010-01-03   
2            2010-339              1     Brisbane     brisbane 2010-01-03   
3            2010-339              1     Brisbane     brisbane 2010-01-03   
4            2010-339              1     Brisbane     brisbane 2010-01-03   
...               ...            ...          ...          ...        ...   
42616        2019-540             39    Wimbledon    wimbledon 2019-07-01   
42617        2019-540             39    Wimbledon    wimbledon 2019-07-01   
42618        2019-540             39    Wimbledon    wimbledon 2019-07-01   
42619        2019-540             39    Wimbledon    wimbledon 2019-07-01   
42620        2019-540             39    Wimbledon    wimbledon 2019-07-01   

        end_date    tourney_round_name  round_order        winner_name  \
0     2010-01-10                Finals            1       Andy Roddick   
1     2010-01-10           Semi-Finals            2       Andy Roddick   
2     2010-01-10           Semi-Finals            2     Radek Stepanek   
3     2010-01-10        Quarter-Finals            3       Andy Roddick   
4     2010-01-10        Quarter-Finals            3     Radek Stepanek   
...          ...                   ...          ...                ...   
42616 2019-07-14  1st Round Qualifying           10           Go Soeda   
42617 2019-07-14  1st Round Qualifying           10      Yuichi Sugita   
42618 2019-07-14  1st Round Qualifying           10  Mikael Torpegaard   
42619 2019-07-14  1st Round Qualifying           10  Yasutaka Uchiyama   
42620 2019-07-14  1st Round Qualifying           10       Donald Young   

      winner_player_id  ... winner_sets_won loser_sets_won winner_games_won  \
0                 r485  ...             2.0            0.0             14.0   
1                 r485  ...             2.0            1.0             13.0   
2                 s694  ...             2.0            0.0             12.0   
3                 r485  ...             2.0            0.0             13.0   
4                 s694  ...             2.0            0.0             13.0   
...                ...  ...             ...            ...              ...   
42616             sc47  ...             2.0            1.0             15.0   
42617             se73  ...             2.0            0.0             12.0   
42618             tc12  ...             2.0            1.0             17.0   
42619             u134  ...             2.0            0.0             13.0   
42620             y124  ...             2.0            0.0             13.0   

      loser_games_won winner_tiebreaks_won loser_tiebreaks_won  \
0                12.0                  2.0                 0.0   
1                13.0                  0.0                 0.0   
2                 3.0                  0.0                 0.0   
3                 9.0                  1.0                 0.0   
4                 7.0                  1.0                 0.0   
...               ...                  ...                 ...   
42616            11.0                  0.0                 0.0   
42617             6.0                  0.0                 0.0   
42618            15.0                  1.0                 0.0   
42619            10.0                  1.0                 0.0   
42620            10.0                  1.0                 0.0   

                           match_id  tourney_year  \
0      2010-339-MS001-8-1-r485-s694          2010   
1      2010-339-MS002-7-2-r485-ba47          2010   
2      2010-339-MS003-7-1-s694-mc65          2010   
3      2010-339-MS004-6-4-r485-g628          2010   
4      2010-339-MS007-6-3-s694-o234          2010   
...                             ...           ...   
42616  2019-540-QS086-1-5-sc47-bm03          2019   
42617  2019-540-QS121-1-4-

<a id = "understanding-preparation-match-stats"></a>

## 4. Data understanding and preparation - Match Stats dataset

[Back to TOC](#toc)

In [67]:
match_stats.T

0      \
match_id                                               2010-339-MS001-8-1-r485-s694   
tourney_slug                                                               brisbane   
match_stats_url_suffix            /en/scores/2010/339/MS001/match-stats?isLive=F...   
match_time                                                                 02:05:00   
match_duration                                                                125.0   
winner_slug                                                                    r485   
winner_serve_rating                                                           304.0   
winner_aces                                                                     7.0   
winner_double_faults                                                            1.0   
winner_first_serves_in                                                         64.0   
winner_first_serves_total                                                      83.0   
winner_first_serve_points_won                                                  45.0   
winner_first_serve_points_total                                                64.0   
winner_second_serve_points_won                                                 13.0   
winner_second_serve_points_total                                               19.0   
winner_break_points_saved                                                       3.0   
winner_break_points_serve_total                                                 5.0   
winner_service_games_played                                                    12.0   
winner_return_rating                                                          119.0   
winner_first_serve_return_won                                                  18.0   
winner_first_serve_return_total                                                56.0   
winner_second_serve_return_won                                                 18.0   
winner_second_serve_return_total                                               39.0   
winner_break_points_converted                                                   2.0   
winner_break_points_return_total                                                8.0   
winner_return_games_played                                                     12.0   
winner_service_points_won                                                      58.0   
winner_service_points_total                                                    83.0   
winner_return_points_won                                                       36.0   
winner_return_points_total                                                     95.0   
winner_total_points_won                                                        94.0   
winner_total_points_total                                                     178.0   
loser_slug                                                                     s694   
loser_serve_rating                                                            261.0   
loser_aces                                                                      5.0   
loser_double_faults                                                             8.0   
loser_first_serves_in                                                          56.0   
loser_first_serves_total                                                       95.0   
loser_first_serve_points_won                                                   38.0   
loser_first_serve_points_total                                                 56.0   
loser_second_serve_points_won                                                  21.0   
loser_second_serve_points_total                                                39.0   
loser_break_points_saved                                                        6.0   
loser_break_points_serve_total                                                  8.0   
loser_service_games_played                                                     12.0   
loser_return_rating                                                         

**Variables**:

- `match_id`
- `tourney_slug`
- `match_stats_url_suffix`
- `match_time`: total duration of the match, in hours and minutes.
- `match_duration`: total duration of the match, in minutes.
- `winner_slug`
- `winner_serve_rating`: calculated by dividing the total number of points won on a player's serve by the total number of service games played; for example, if a player wins 80 points out of 100 service points played, their serve rating would be 80%. Is used to measure how effective a player's serve is in winning points and games. Players with a high serve rating are generally able to hold their serve more easily and put pressure on their opponent.
- `winner_aces`: number of aces for the player. An ace is a serve that is not touched by the receiver and lands inside the service box, resulting in a point for the server.
- `winner_double_faults`: number of double faults for the player. A double fault is a serve that fails to land in the opponent's service box, resulting in a point for the opponent. A double fault occurs when a player misses both their first and second serves, or commits a fault on their second serve.
- `winner_first_serves_in`: number of first serves-in for the player. A player is allowed two attempts to serve the ball into the opponent's service box. If the first serve is unsuccessful, they get a second attempt, which is known as the second serve. So, this variable stores the number of first serves-in refers to the number of times a player successfully lands their first serve in the opponent's service box during a match.
- `winner_first_serves_total`: number of first serves in the total for the player.
- `winner_first_serve_points_won`: number of points gained in the player's first serve.
- `winner_first_serve_points_total`: number of points played in the player's first serve.
- `winner_second_serve_points_won`: number of points gained in the player's second serve.
- `winner_second_serve_points_total`: number of points played in the player's second serve.
- `winner_break_points_saved`: a break point is a situation in which the receiver has the opportunity to win a game on the server's next service game. A break point occurs when the receiver wins a point during the server's service game, putting them in a position to potentially win the game by breaking their opponent's serve. So this variables stores the number of break points that the player saved.
- `winner_break_points_serve_total`: the number of break points that the player was faced to.
- `winner_service_games_played`: number of games that the player is serving played.
- `winner_return_rating`: the return rate refers to the percentage of return points won by a player during the match. A return point is any point in which the player is receiving serve and has the opportunity to win the point by returning the serve and subsequently winning the rally.
- `winner_first_serve_return_won`: number of points gained, by returning to the first serve of the other player.
- `winner_first_serve_return_total`: number of points played, by returning to the first serve of the other player.
- `winner_second_serve_return_won`: number of points gained, by returning to the second serve of the other player.
- `winner_second_serve_return_total`: number of points played, by returning to the second serve of the other player.
- `winner_break_points_converted`: number of break point opportunities that the player successfully converts into service breaks during the match.
- `winner_break_points_return_total`: number of break point opportunities that the player had during the match.
- `winner_return_games_played`: number of games that the player had to return the other player's service.
- `winner_service_points_won`: number of points won during the service of the player.
- `winner_service_points_total`: number of points played during the service of the player.
- `winner_return_points_won`: number of points won by returning the other player's service.
- `winner_return_points_total`: number of points played by returning the other player's service.
- `winner_total_points_won`: number of points won by the player, independently of the service.
- `winner_total_points_total`: number of points played.
- `loser_slug`
- `loser_serve_rating`: calculated by dividing the total number of points won on a player's serve by the total number of service games played.
- `loser_aces`: number of aces for the player.
- `loser_double_faults`: number of double faults for the player.
- `loser_first_serves_in`: number of first serves-in for the player. This variable stores the number of first serves-in refers to the number of times a player successfully lands their first serve in the opponent's service box during the match.
- `loser_first_serves_total`: number of first serves in the total for the player.
- `loser_first_serve_points_won`: number of points gained in the player's first serve.
- `loser_first_serve_points_total`: number of points played in the player's first serve.
- `loser_second_serve_points_won`: number of points gained in the player's second serve.
- `loser_second_serve_points_total`: number of points played in the player's second serve.
- `loser_break_points_saved`: the number of break points that the player saved.
- `loser_break_points_serve_total`: the number of break points that the player was faced to.
- `loser_service_games_played`: number of games that the player is serving played.
- `loser_return_rating`: percentage of return points won by a player during the match.
- `loser_first_serve_return_won`: number of points gained, by returning to the first serve of the other player.
- `loser_first_serve_return_total`: number of points played, by returning to the first serve of the other player.
- `loser_second_serve_return_won`: number of points gained, by returning to the second serve of the other player.
- `loser_second_serve_return_total`: number of points played, by returning to the second serve of the other player.
- `loser_break_points_converted`: number of break point opportunities that the player successfully converts into service breaks during the match.
- `loser_break_points_return_total`: number of break point opportunities that the player had during the match.
- `loser_return_games_played`: number of games that the player had to return the other player's service.
- `loser_service_points_won`: number of points won during the service of the player.
- `loser_service_points_total`: number of points played during the service of the player.
- `loser_return_points_won`: number of points won by returning the other player's service.
- `loser_return_points_total`: number of points played by returning the other player's service.
- `loser_total_points_won`: number of points won by the player, independently of the service.
- `loser_total_points_total`: number of points played.

In [68]:
# checking the shape of the dataset

match_stats.shape

(42447, 59)

This dataset has an observation for each match, therefore, should be merged with the previous one by `match_id` that is a uniquely identifier for each observation.

#### Data types:

In [69]:
# checking the types of the variables, as well as the number of non-null observations in each variable

match_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42447 entries, 0 to 42446
Data columns (total 59 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   match_id                          42447 non-null  object 
 1   tourney_slug                      42447 non-null  object 
 2   match_stats_url_suffix            42447 non-null  object 
 3   match_time                        42443 non-null  object 
 4   match_duration                    42443 non-null  float64
 5   winner_slug                       42443 non-null  object 
 6   winner_serve_rating               42443 non-null  float64
 7   winner_aces                       42443 non-null  float64
 8   winner_double_faults              42443 non-null  float64
 9   winner_first_serves_in            42443 non-null  float64
 10  winner_first_serves_total         42443 non-null  float64
 11  winner_first_serve_points_won     42443 non-null  float64
 12  winn

There are 4 matches that have multiple missing values in almost all variables. That should be investigated in detail.

In [70]:
# storing correctly the variable regarding time

match_stats['match_time'] = pd.to_datetime(match_stats['match_time'], format = '%H:%M:%S')

#### Descriptive statistics:

In [71]:
match_stats.describe().T

count        mean        std   min    25%  \
match_duration                    42443.0  101.715831  39.158675   2.0   74.0   
winner_serve_rating               42443.0  282.597649  44.751406   0.0  268.0   
winner_aces                       42443.0    6.361779   5.329839   0.0    3.0   
winner_double_faults              42443.0    2.523078   2.202477   0.0    1.0   
winner_first_serves_in            42443.0   45.430436  18.543442   0.0   33.0   
winner_first_serves_total         42443.0   73.549136  28.674691   0.0   54.0   
winner_first_serve_points_won     42443.0   34.329807  13.386354   0.0   26.0   
winner_first_serve_points_total   42443.0   45.430436  18.543442   0.0   33.0   
winner_second_serve_points_won    42443.0   15.619395   6.786309   0.0   11.0   
winner_second_serve_points_total  42443.0   28.118700  12.574635   0.0   20.0   
winner_break_points_saved         42443.0    3.272247   2.980732  -7.0    1.0   
winner_break_points_serve_total   42443.0    4.743821   3.868447   0.0    2.0   
winner_service_games_played       42443.0   11.785029   4.168166   0.0    9.0   
winner_return_rating              42443.0  170.509083  48.174174   0.0  143.0   
winner_first_serve_return_won     42443.0   15.460641   6.749674   0.0   11.0   
winner_first_serve_return_total   42443.0   45.900125  18.879860   0.0   33.0   
winner_second_serve_return_won    42443.0   16.475438   6.808634   0.0   12.0   
winner_second_serve_return_total  42443.0   30.457249  12.527065   0.0   22.0   
winner_break_points_converted     42443.0    3.701105   1.635369   0.0    3.0   
winner_break_points_return_total  42443.0    8.234644   3.987552   0.0    6.0   
winner_return_games_played        42443.0   11.596918   4.170696   0.0    9.0   
winner_service_points_won         42443.0   49.949202  18.215048   0.0   38.0   
winner_service_points_total       42443.0   73.549136  28.674691   0.0   54.0   
winner_return_points_won          42443.0   31.936079  11.139744   0.0   25.0   
winner_return_points_total        42443.0   76.357373  28.737296   0.0   57.0   
winner_total_points_won           42443.0   81.885281  27.019816   0.0   64.0   
winner_total_points_total         42443.0  149.906510  55.846267   0.0  112.0   
loser_serve_rating                42443.0  232.694484  46.573048  -2.0  213.0   
loser_aces                        42443.0    4.684165   4.622071   0.0    2.0   
loser_double_faults               42443.0    3.265061   2.440933   0.0    1.0   
loser_first_serves_in             42443.0   45.968475  18.806744   0.0   33.0   
loser_first_serves_total          42443.0   76.464175  28.599390   0.0   57.0   
loser_first_serve_points_won      42443.0   30.483543  14.082759   0.0   21.0   
loser_first_serve_points_total    42443.0   45.968475  18.806744   0.0   33.0   
loser_second_serve_points_won     42443.0   14.002898   6.980890   0.0    9.0   
loser_second_serve_points_total   42443.0   30.495700  12.478434   0.0   22.0   
loser_break_points_saved          42443.0    4.537521   3.175627 -10.0    2.0   
loser_break_points_serve_total    42443.0    8.233278   3.989027   0.0    6.0   
loser_service_games_played        42443.0   11.596918   4.170696   0.0    9.0   
loser_return_rating               42443.0  106.456636  45.968165   0.0   64.0   
loser_first_serve_return_won      42443.0   11.083524   6.674144   0.0    6.0   
loser_first_serve_return_total    42443.0   45.366680  18.617534   0.0   33.0   
loser_second_serve_return_won     42443.0   12.486299   6.896829   0.0    8.0   
loser_second_serve_return_total   42443.0   28.080367  12.614653   0.0   19.0   
loser_break_points_converted      42443.0    1.474684   1.468754   0.0    0.0   
loser_break_points_return_total   42443.0    4.744457   3.868078   0.0    2.0   
loser_return_games_played         42443.0   11.785029   4.168166   0.0    9.0   
loser_service_points_won          42443.0   44.486441  19.447181   0.0   31.0   
loser_service_points_total        42443.0   76.464175  28.599390   

In [72]:
match_stats.describe(include = ['O']).T

count unique  \
match_id                42447  42447   
tourney_slug            42447     95   
match_stats_url_suffix  42447  42447   
winner_slug             42443   1188   
loser_slug              42443   2120   

                                                                      top  \
match_id                                     2010-339-MS001-8-1-r485-s694   
tourney_slug                                              australian-open   
match_stats_url_suffix  /en/scores/2010/339/MS001/match-stats?isLive=F...   
winner_slug                                                          d643   
loser_slug                                                           r772   

                        freq  
match_id                   1  
tourney_slug            2386  
match_stats_url_suffix     1  
winner_slug              608  
loser_slug               256

From this descriptive statistics, we can see that the average game lasts for 102 minutes, and on average the match has 150 points played. It would be interesting to know which players are the ones that win more and that lose more. To do that, we need to merge the two datasets (this one and the one with match scores), but this slug information do not add that much, therefore these two variables (`winner_slug` and `loser_slug`) should be deleted.

#### Do not make sense for our analysis:

Again, we have URL in the dataset (`match_stats_url_suffix`), that does not make sense for our analysis, therefore will also be deleted. The same happens for the `match_order`, as it is irrelevant to know what were the matches that played before or after in the same round (the only thing that matters is the round).

In [73]:
# dropping the variables as explained before

match_stats.drop(columns = ['match_stats_url_suffix'], inplace = True)

In [74]:
# dropping the variables as explained before

match_stats.drop(columns = ['winner_slug', 'loser_slug'], inplace = True)

#### Missing values:

In [75]:
# creating a copy to solve the problems with missing values

match_stats_missing = match_stats.copy()

In [76]:
# replacing other types of missing values not recognized by pandas with NaN and checking again the number of missing values

match_stats_missing.replace(missing_values, np.nan, inplace = True)
match_stats_missing.isna().sum()

match_id                            0
tourney_slug                        0
match_time                          4
match_duration                      4
winner_serve_rating                 4
winner_aces                         4
winner_double_faults                4
winner_first_serves_in              4
winner_first_serves_total           4
winner_first_serve_points_won       4
winner_first_serve_points_total     4
winner_second_serve_points_won      4
winner_second_serve_points_total    4
winner_break_points_saved           4
winner_break_points_serve_total     4
winner_service_games_played         4
winner_return_rating                4
winner_first_serve_return_won       4
winner_first_serve_return_total     4
winner_second_serve_return_won      4
winner_second_serve_return_total    4
winner_break_points_converted       4
winner_break_points_return_total    4
winner_return_games_played          4
winner_service_points_won           4
winner_service_points_total         4
winner_retur

In [77]:
# seeing rows with NaNs

match_stats_nans_index = match_stats_missing.isna().any(axis = 1)
match_stats_missing[match_stats_nans_index]

match_id    tourney_slug match_time  \
1806    2010-468-QS008-2-7-p701-n605         estoril        NaT   
1810    2010-468-QS015-2-2-m984-bd42         estoril        NaT   
39269  2019-6932-QS015-1-2-mo44-d0ar  rio-de-janeiro        NaT   
39677  2019-403-MS086-3-21-h756-l797           miami        NaT   

       match_duration  winner_serve_rating  winner_aces  winner_double_faults  \
1806              NaN                  NaN          NaN                   NaN   
1810              NaN                  NaN          NaN                   NaN   
39269             NaN                  NaN          NaN                   NaN   
39677             NaN                  NaN          NaN                   NaN   

       winner_first_serves_in  winner_first_serves_total  \
1806                      NaN                        NaN   
1810                      NaN                        NaN   
39269                     NaN                        NaN   
39677                     NaN                        NaN   

       winner_first_serve_points_won  ...  loser_second_serve_return_total  \
1806                             NaN  ...                              NaN   
1810                             NaN  ...                              NaN   
39269                            NaN  ...                              NaN   
39677                            NaN  ...                              NaN   

       loser_break_points_converted  loser_break_points_return_total  \
1806                            NaN                              NaN   
1810                            NaN                              NaN   
39269                           NaN                              NaN   
39677                           NaN                              NaN   

       loser_return_games_played  loser_service_points_won  \
1806                         NaN                       NaN   
1810                         NaN                       NaN   
39269                        NaN                       NaN   
39677                        NaN                       NaN   

       loser_service_points_total  loser_return_points_won  \
1806                          NaN                      NaN   
1810                          NaN                      NaN   
39269                         NaN                      NaN   
39677                         NaN                      NaN   

       loser_return_points_total  loser_total_points_won  \
1806                         NaN                     NaN   
1810                         NaN                     NaN   
39269                        NaN                     NaN   
39677                        NaN                     NaN   

       loser_total_points_total  
1806                        NaN  
1810                        NaN  
39269                       NaN  
39677                       NaN  

[4 rows x 56 columns]

In [78]:
# list with the match_id of the observations with missing values
match_id_missing = ['2010-468-QS008-2-7-p701-n605', '2010-468-QS015-2-2-m984-bd42', '2019-6932-QS015-1-2-mo44-d0ar', '2019-403-MS086-3-21-h756-l797']

# using the match_id to search in the match_scores dataset the specific matches
match_scores[match_scores['match_id'].isin(match_id_missing)].T

18171  \
tourney_year_id                                              2019-6932   
tourney_order                                                       13   
tourney_name                                            Rio de Janeiro   
tourney_slug                                            rio-de-janeiro   
start_date                                         2019-02-18 00:00:00   
end_date                                           2019-02-24 00:00:00   
tourney_round_name                                1st Round Qualifying   
round_order                                                          7   
winner_name                                             Pedro Martinez   
winner_player_id                                                  mo44   
winner_slug                                             pedro-martinez   
loser_name                            Mateus De Carvalho Cardoso Alves   
loser_player_id                                                   d0ar   
loser_slug                            mateus-de-carvalho-cardoso-alves   
winner_seed                                                          8   
loser_seed                                                          WC   
match_score_tiebreaks                                         64 36 75   
winner_sets_won                                                    2.0   
loser_sets_won                                                     1.0   
winner_games_won                                                  16.0   
loser_games_won                                                   15.0   
winner_tiebreaks_won                                               0.0   
loser_tiebreaks_won                                                0.0   
match_id                                 2019-6932-QS015-1-2-mo44-d0ar   
tourney_year                                                      2019   
pair                   Mateus De Carvalho Cardoso Alves-Pedro Martinez   
prize_money_USD                                              1786690.0   

                                               18546  \
tourney_year_id                             2019-403   
tourney_order                                     20   
tourney_name                  ATP Masters 1000 Miami   
tourney_slug                                   miami   
start_date                       2019-03-20 00:00:00   
end_date                         2019-03-31 00:00:00   
tourney_round_name                      Round of 128   
round_order                                        7   
winner_name                              Robin Haase   
winner_player_id                                h756   
winner_slug                              robin-haase   
loser_name                               Lukas Lacko   
loser_player_id                                 l797   
loser_slug                               lukas-lacko   
winner_seed                           Not applicable   
loser_seed                                         Q   
match_score_tiebreaks                          62 64   
winner_sets_won                                  2.0   
loser_sets_won                                   0.0   
winner_games_won                                12.0   
loser_games_won                                  6.0   
winner_tiebreaks_won                             0.0   
loser_tiebreaks_won                              0.0   
match_id               2019-403-MS086-3-21-h756-l797   
tourney_year                                    2019   
pair                         Lukas Lacko-Robin Haase   
prize_money_USD                            8359455.0   

                                                      22534  \
tourney_year_id                                    2010-468   
tourney_order                                            27   
tourney_name                                        Estoril   
tourney_slug                                        estoril   
start_date                              2010-05-03 00:00:00   
end_date                                2010-

After a search on the internet (and specially websites that have tennis statistics like ATP tour or flashscore) we did not found the statistics regarding these games. Adding the fact that these games are not that important to the analysis that is going to be made (3 matches are from the qualifying draw and the other one is from round of 128, so they are not really decisive), these games will be deleted from the dataset. 

In [79]:
# droping those observations

match_stats_missing.dropna(inplace = True)

In [80]:
# keeping the dataframe without missing values

match_stats = match_stats_missing.copy()

For the dashboard created we want to plot some relevant statistics from the matches to have a better understanding of the performance of players. Therefore we need to have the data normalized in the same scale to plot it. The variables that are going to be used are: 'winner_aces', 'winner_break_points_converted', 'winner_break_points_saved', 'winner_double_faults', 'winner_return_points_won', 'winner_total_points_won', 'loser_aces', 'loser_break_points_converted', 'loser_break_points_saved', 'loser_double_faults', 'loser_return_points_won', and 'loser_total_points_won'. So, those will be normalized using MinMaxScaler, forcing the range to be between 0 and 10. 

In [81]:
# defining the statistics that are going to be displayed in the radar chart
skills = ['winner_aces', 'winner_break_points_converted', 'winner_break_points_saved', 'winner_double_faults', 'winner_return_points_won', 'winner_total_points_won', 'loser_aces', 'loser_break_points_converted', 'loser_break_points_saved', 'loser_double_faults', 'loser_return_points_won', 'loser_total_points_won']

# defining an instance of MinMaxScaler
scaler = MinMaxScaler(feature_range = (0, 10))

# scaling the data, making sure that all data will be in the range 0-10 and assigning the scaled data to the dataframe
match_stats[[col + '_norm' for col in skills]] = scaler.fit_transform(match_stats[skills])

Also, for constructing the dashboard we will need to see the maximum number of aces and the maximum number of break points saved, independetly if the player was loser or winner. So, two columns will be created storing the maximum number of those statistics for each match.

In [82]:
# creating the columns with the maximum values of the statistics

match_stats['max_aces'] = match_stats[['winner_aces', 'loser_aces']].max(axis = 1)
match_stats['max_break_points_saved'] = match_stats[['winner_break_points_saved', 'loser_break_points_saved']].max(axis = 1)

In [83]:
match_stats

match_id      tourney_slug          match_time  \
0      2010-339-MS001-8-1-r485-s694          brisbane 1900-01-01 02:05:00   
1      2010-339-MS002-7-2-r485-ba47          brisbane 1900-01-01 02:08:00   
2      2010-339-MS003-7-1-s694-mc65          brisbane 1900-01-01 01:01:00   
3      2010-339-MS004-6-4-r485-g628          brisbane 1900-01-01 01:25:00   
4      2010-339-MS007-6-3-s694-o234          brisbane 1900-01-01 01:40:00   
...                             ...               ...                 ...   
42442  2019-605-MS020-1-5-f324-bk40  nitto-atp-finals 1900-01-01 01:18:00   
42443  2019-605-MS010-1-4-z355-n409  nitto-atp-finals 1900-01-01 01:24:00   
42444  2019-605-MS011-1-3-te51-mm58  nitto-atp-finals 1900-01-01 01:42:00   
42445  2019-605-MS018-1-2-d643-bk40  nitto-atp-finals 1900-01-01 01:04:00   
42446  2019-605-MS019-1-1-tb69-f324  nitto-atp-finals 1900-01-01 01:40:00   

       match_duration  winner_serve_rating  winner_aces  winner_double_faults  \
0               125.0                304.0          7.0                   1.0   
1               128.0                288.0          7.0                   1.0   
2                61.0                309.0          3.0                   0.0   
3                85.0                344.0         16.0                   1.0   
4               100.0                279.0          7.0                   4.0   
...               ...                  ...          ...                   ...   
42442            78.0                321.0          8.0                   0.0   
42443            84.0                313.0         11.0                   2.0   
42444           102.0                295.0          5.0                   0.0   
42445            64.0                300.0          4.0                   1.0   
42446           100.0                282.0          1.0                   1.0   

       winner_first_serves_in  winner_first_serves_total  \
0                        64.0                       83.0   
1                        60.0                       81.0   
2                        31.0                       50.0   
3                        45.0                       60.0   
4                        33.0                       61.0   
...                       ...                        ...   
42442                    45.0                       67.0   
42443                    34.0                       49.0   
42444                    44.0                       73.0   
42445                    24.0                       40.0   
42446                    51.0                       81.0   

       winner_first_serve_points_won  ...  winner_return_points_won_norm  \
0                               45.0  ...                       3.461538   
1                               43.0  ...                       3.173077   
2                               20.0  ...                       2.307692   
3                               39.0  ...                       2.115385   
4                               24.0  ...                       3.173077   
...                              ...  ...                            ...   
42442                           35.0  ...                       2.115385   
42443                           30.0  ...                       2.596154   
42444                           39.0  ...                       2.500000   
42445                           18.0  ...                       2.692308   
42446                           33.0  ...                       2.403846   

       winner_total_points_won_norm  loser_aces_norm  \
0                          1.966527         0.485437   
1                          1.820084         1.165049   
2                          1.234310         0.097087   
3                          1.485356         0.582524   
4                          1.548117         0.291262   
...                             ...              ...   
42442                      1.506276         0.582524   
42443                      1.338912         0.4

<a id = "merging-match-scores-stats"></a>

## 5. Merging the stats dataset with the score dataset

[Back to TOC](#toc)

In [84]:
# merging the two datasets

all_match = pd.merge(match_scores, match_stats, how = 'left', on = 'match_id', suffixes = ('_match_scores', '_match_stats'))
all_match

tourney_year_id  tourney_order tourney_name tourney_slug_match_scores  \
0            2010-339              1     Brisbane                  brisbane   
1            2010-339              1     Brisbane                  brisbane   
2            2010-339              1     Brisbane                  brisbane   
3            2010-339              1     Brisbane                  brisbane   
4            2010-339              1     Brisbane                  brisbane   
...               ...            ...          ...                       ...   
42616        2019-540             39    Wimbledon                 wimbledon   
42617        2019-540             39    Wimbledon                 wimbledon   
42618        2019-540             39    Wimbledon                 wimbledon   
42619        2019-540             39    Wimbledon                 wimbledon   
42620        2019-540             39    Wimbledon                 wimbledon   

      start_date   end_date    tourney_round_name  round_order  \
0     2010-01-03 2010-01-10                Finals            1   
1     2010-01-03 2010-01-10           Semi-Finals            2   
2     2010-01-03 2010-01-10           Semi-Finals            2   
3     2010-01-03 2010-01-10        Quarter-Finals            3   
4     2010-01-03 2010-01-10        Quarter-Finals            3   
...          ...        ...                   ...          ...   
42616 2019-07-01 2019-07-14  1st Round Qualifying           10   
42617 2019-07-01 2019-07-14  1st Round Qualifying           10   
42618 2019-07-01 2019-07-14  1st Round Qualifying           10   
42619 2019-07-01 2019-07-14  1st Round Qualifying           10   
42620 2019-07-01 2019-07-14  1st Round Qualifying           10   

             winner_name winner_player_id  ... winner_return_points_won_norm  \
0           Andy Roddick             r485  ...                      3.461538   
1           Andy Roddick             r485  ...                      3.173077   
2         Radek Stepanek             s694  ...                      2.307692   
3           Andy Roddick             r485  ...                      2.115385   
4         Radek Stepanek             s694  ...                      3.173077   
...                  ...              ...  ...                           ...   
42616           Go Soeda             sc47  ...                      2.692308   
42617      Yuichi Sugita             se73  ...                      2.019231   
42618  Mikael Torpegaard             tc12  ...                      2.692308   
42619  Yasutaka Uchiyama             u134  ...                      2.403846   
42620       Donald Young             y124  ...                      1.730769   

      winner_total_points_won_norm loser_aces_norm  \
0                         1.966527        0.485437   
1                         1.820084        1.165049   
2                         1.234310        0.097087   
3                         1.485356        0.582524   
4                         1.548117        0.291262   
...                            ...             ...   
42616                     1.924686        0.291262   
42617                     1.192469        0.388350   
42618                     2.029289        0.582524   
42619                     1.694561        0.485437   
42620                     1.527197        1.067961   

      loser_break_points_converted_norm loser_break_points_saved_norm  \
0                              0.769231                      2.857143   
1                              0.769231                      3.571429   
2                              0.000000                      2.321429   
3                              0.000000                      3.035714   
4                              0.384615                      2.857143   
...                                 ...                           ...   
42616                          0.384615                      1.785714   
42617                          0.000000                      1.785714 

In [85]:
# checking the missing values of the merged dataset

all_match.isna().sum()

tourney_year_id                   0
tourney_order                     0
tourney_name                      0
tourney_slug_match_scores         0
start_date                        0
                               ... 
loser_double_faults_norm        304
loser_return_points_won_norm    304
loser_total_points_won_norm     304
max_aces                        304
max_break_points_saved          304
Length: 96, dtype: int64

In [86]:
pd.set_option('display.max_rows', 350)

# seeing rows with NaNs
all_match_nans_index = all_match.isna().any(axis = 1)
missing = all_match[all_match_nans_index]
missing

tourney_year_id  tourney_order                   tourney_name  \
84           2010-451              2                           Doha   
85           2010-451              2                           Doha   
86           2010-451              2                           Doha   
87           2010-451              2                           Doha   
89           2010-451              2                           Doha   
313         2010-5012              7                   Johannesburg   
546          2010-506             15                   Buenos Aires   
641          2010-495             16                          Dubai   
693          2010-499             18                   Delray Beach   
763          2010-404             19  ATP Masters 1000 Indian Wells   
772          2010-404             19  ATP Masters 1000 Indian Wells   
800          2010-404             19  ATP Masters 1000 Indian Wells   
1054         2010-717             21                        Houston   
1095         2010-315             38                        Newport   
1370         2010-422             48    ATP Masters 1000 Cincinnati   
1853         2010-747             55                        Beijing   
1894         2010-329             56                          Tokyo   
2294         2011-891              3                        Chennai   
2340         2011-338              4                         Sydney   
2402         2011-301              5                       Auckland   
2406         2011-301              5                       Auckland   
2528         2011-424             11                       San Jose   
2883         2011-404             19  ATP Masters 1000 Indian Wells   
3964        2011-1720             55                        Bangkok   
3965        2011-1720             55                        Bangkok   
3968        2011-1720             55                        Bangkok   
4072        2011-5014             58      ATP Masters 1000 Shanghai   
4275         2012-339              1                       Brisbane   
4322         2012-451              2                           Doha   
4332         2012-451              2                           Doha   
4387         2012-891              3                        Chennai   
4983         2012-404             19  ATP Masters 1000 Indian Wells   
5012         2012-404             19  ATP Masters 1000 Indian Wells   
5087         2012-403             20         ATP Masters 1000 Miami   
5103         2012-403             20         ATP Masters 1000 Miami   
5243         2012-717             21                        Houston   
5484         2012-421             50        ATP Masters 1000 Canada   
5699         2012-560             53                        US Open   
6009        2012-6003             56                   Kuala Lumpur   
6081         2012-747             58                        Beijing   
6176        2012-5014             60      ATP Masters 1000 Shanghai   
6565         2013-301              5                       Auckland   
6570         2013-301              5                       Auckland   
6590         2013-505              8                   Vina del Mar   
6759         2013-402             13                        Memphis   
7014         2013-404             19  ATP Masters 1000 Indian Wells   
7043         2013-404             19  ATP Masters 1000 Indian Wells   
7096         2013-404             19  ATP Masters 1000 Indian Wells   
7153         2013-403             20         ATP Masters 1000 Miami   
7160         2013-403             20         ATP Masters 1000 Miami   
8157         2013-747             56                        Beijing   
8245        2013-5014             58      ATP Masters 1000 Shanghai   
8478         2014-451              2                           Doha   
8504         2014-891              3                        Chennai   
8585         2014-301              4                       Auckland   
8687         2014-505         

In [87]:
# confirming if there are some missing information regarding match stats for finals matches

missing[missing['tourney_round_name'] == 'finals']

Empty DataFrame
Columns: [tourney_year_id, tourney_order, tourney_name, tourney_slug_match_scores, start_date, end_date, tourney_round_name, round_order, winner_name, winner_player_id, winner_slug, loser_name, loser_player_id, loser_slug, winner_seed, loser_seed, match_score_tiebreaks, winner_sets_won, loser_sets_won, winner_games_won, loser_games_won, winner_tiebreaks_won, loser_tiebreaks_won, match_id, tourney_year, pair, prize_money_USD, tourney_slug_match_stats, match_time, match_duration, winner_serve_rating, winner_aces, winner_double_faults, winner_first_serves_in, winner_first_serves_total, winner_first_serve_points_won, winner_first_serve_points_total, winner_second_serve_points_won, winner_second_serve_points_total, winner_break_points_saved, winner_break_points_serve_total, winner_service_games_played, winner_return_rating, winner_first_serve_return_won, winner_first_serve_return_total, winner_second_serve_return_won, winner_second_serve_return_total, winner_break_points_converted, winner_break_points_return_total, winner_return_games_played, winner_service_points_won, winner_service_points_total, winner_return_points_won, winner_return_points_total, winner_total_points_won, winner_total_points_total, loser_serve_rating, loser_aces, loser_double_faults, loser_first_serves_in, loser_first_serves_total, loser_first_serve_points_won, loser_first_serve_points_total, loser_second_serve_points_won, loser_second_serve_points_total, loser_break_points_saved, loser_break_points_serve_total, loser_service_games_played, loser_return_rating, loser_first_serve_return_won, loser_first_serve_return_total, loser_second_serve_return_won, loser_second_serve_return_total, loser_break_points_converted, loser_break_points_return_total, loser_return_games_played, loser_service_points_won, loser_service_points_total, loser_return_points_won, loser_return_points_total, loser_total_points_won, loser_total_points_total, winner_aces_norm, winner_break_points_converted_norm, winner_break_points_saved_norm, winner_double_faults_norm, winner_return_points_won_norm, winner_total_points_won_norm, loser_aces_norm, loser_break_points_converted_norm, loser_break_points_saved_norm, loser_double_faults_norm, loser_return_points_won_norm, loser_total_points_won_norm, max_aces, max_break_points_saved]
Index: []

[0 rows x 96 columns]

After seeing all of the information (the dataset with the missing values), we conclude that these missing values appear to be caused because there are no information regarding statistics for that game in the `match_stats` dataset. Therefore, since our analysis will only include statistics for the final match, and there are no missing information regarding those games, we decided that these rows with missing values can be deleted.

In [88]:
# dropping the observations

all_match.dropna(inplace = True)

After starting constructing of the dashboard, we noticed that it was being too slow, maybe due to the high number of features and observations in the datasets. Therefore, we decided to drop the variables and observations that were not needed for the analysis.

In [89]:
all_match = all_match[['tourney_name', 'tourney_round_name', 'round_order', 'match_duration', 'winner_name', 'loser_name', 'winner_aces', 'tourney_year', 'winner_break_points_converted',
                      'winner_double_faults', 'winner_return_points_won', 'winner_total_points_won', 'winner_aces_norm', 'winner_break_points_converted_norm', 'winner_break_points_saved_norm',
                      'winner_double_faults_norm', 'winner_return_points_won_norm', 'winner_total_points_won_norm', 'loser_aces', 'loser_break_points_converted', 'loser_break_points_saved',
                      'loser_double_faults', 'loser_return_points_won', 'loser_total_points_won', 'loser_aces_norm', 'loser_break_points_converted_norm', 'loser_break_points_saved_norm',
                      'loser_double_faults_norm', 'loser_return_points_won_norm', 'loser_total_points_won_norm', 'winner_break_points_saved', 'pair', 'max_break_points_saved', 'max_aces']]

all_match

tourney_name    tourney_round_name  round_order  match_duration  \
0         Brisbane                Finals            1           125.0   
1         Brisbane           Semi-Finals            2           128.0   
2         Brisbane           Semi-Finals            2            61.0   
3         Brisbane        Quarter-Finals            3            85.0   
4         Brisbane        Quarter-Finals            3           100.0   
...            ...                   ...          ...             ...   
42616    Wimbledon  1st Round Qualifying           10           109.0   
42617    Wimbledon  1st Round Qualifying           10            64.0   
42618    Wimbledon  1st Round Qualifying           10           124.0   
42619    Wimbledon  1st Round Qualifying           10            92.0   
42620    Wimbledon  1st Round Qualifying           10            83.0   

             winner_name        loser_name  winner_aces  tourney_year  \
0           Andy Roddick    Radek Stepanek          7.0          2010   
1           Andy Roddick     Tomas Berdych          7.0          2010   
2         Radek Stepanek      Gael Monfils          3.0          2010   
3           Andy Roddick   Richard Gasquet         16.0          2010   
4         Radek Stepanek     Wayne Odesnik          7.0          2010   
...                  ...               ...          ...           ...   
42616           Go Soeda     Filippo Baldi          4.0          2019   
42617      Yuichi Sugita    Carlos Berlocq          2.0          2019   
42618  Mikael Torpegaard  Nikola Milojevic          6.0          2019   
42619  Yasutaka Uchiyama       Jack Draper         14.0          2019   
42620       Donald Young    Egor Gerasimov          2.0          2019   

       winner_break_points_converted  winner_double_faults  ...  \
0                                2.0                   1.0  ...   
1                                2.0                   1.0  ...   
2                                4.0                   0.0  ...   
3                                1.0                   1.0  ...   
4                                4.0                   4.0  ...   
...                              ...                   ...  ...   
42616                            3.0                   1.0  ...   
42617                            3.0                   0.0  ...   
42618                            3.0                   3.0  ...   
42619                            2.0                   1.0  ...   
42620                            2.0                   3.0  ...   

       loser_aces_norm  loser_break_points_converted_norm  \
0             0.485437                           0.769231   
1             1.165049                           0.769231   
2             0.097087                           0.000000   
3             0.582524                           0.000000   
4             0.291262                           0.384615   
...                ...                                ...   
42616         0.291262                           0.384615   
42617         0.388350                           0.000000   
42618         0.582524                           1.153846   
42619         0.485437                           0.384615   
42620         1.067961                           0.384615   

       loser_break_points_saved_norm  loser_double_faults_norm  \
0                           2.857143                  3.809524   
1                           3.571429                  0.952381   
2                           2.321429                  1.428571   
3                           3.035714                  0.952381   
4                           2.857143                  1.428571   
...                              ...                       ...   
42616                       1.785714                  1.428571   
42617                       1.785714                  1.428571   
42618                       2.142857                  0.952381   
42619                       2.142857                  

In [90]:
# saving the datasets already prepared to csv files

all_match.to_csv('all_match_preparation.csv')
tournaments.to_csv('tournaments_preparation.csv')